'use strict';
const APPROVED=['2db9b94c06ad8ba4ce5f1e08187ac632f9dba75ce8a7611b65b859e2676da8f4'], $=id=>document.getElementById(id);
let db,app=null,shellReady=false;
async function database(){if(db)return db;db=await new Promise((resolve,reject)=>{const q=indexedDB.open('oz-planner-launcher-v1',1);q.onupgradeneeded=()=>q.result.createObjectStore('app');q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(Error('This browser could not save the app. Use Safari or a supported installed web app.'));});return db;}
async function record(mode,fn){const d=await database();return new Promise((resolve,reject)=>{let result;const t=d.transaction('app',mode),q=fn(t.objectStore('app'));q.onsuccess=()=>result=q.result;t.oncomplete=()=>resolve(result);t.onerror=()=>reject(Error('The app could not be saved on this device.'));});}
function status(){const s=shellReady?'Launcher ready offline.':'Launcher caching is not complete.';$('status').textContent=s+(app?' Purchased app imported. Close and reopen in Airplane Mode to verify.':' Import your purchased app to finish.');$('open').hidden=!app;$('options').hidden=!app;}
function openApp(){if(!app)return;$('setup').hidden=true;$('app-frame').srcdoc=app.html;$('app-frame').hidden=false;$('app-bar').hidden=false;}
function showSetup(){if(!$('app-frame').hidden&&!confirm('Save a backup inside the app first if you have not already. Return to launcher options?'))return;$('setup').hidden=false;$('app-frame').hidden=true;$('app-frame').removeAttribute('srcdoc');$('app-bar').hidden=true;status();}
$('manage').onclick=showSetup;$('open').onclick=openApp;
$('import').onclick=$('replace').onclick=()=>{$('app-file').value='';$('app-file').click();};
$('app-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>3000000||file.size<100000)throw Error('Choose the original C01-Household-Planner.html from your standalone planner purchase.');$('status').textContent='Verifying your app on this device…';const buffer=await file.arrayBuffer(),hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',buffer))].map(x=>x.toString(16).padStart(2,'0')).join('');if(!APPROVED.includes(hash))throw Error('This file is not an approved app edition for this launcher. Choose the original HTML delivered with your planner purchase, or reopen the installation link online to update the launcher.');const html=new TextDecoder().decode(buffer);app={html,hash,importedAt:new Date().toISOString()};await record('readwrite',s=>s.put(app,'current'));status();}catch(err){$('status').textContent=err.message;}};
$('forget').onclick=async()=>{if(!confirm('Remove the imported app software from this launcher? Keep the purchased HTML and an editable plan backup before continuing.'))return;try{await record('readwrite',s=>s.delete('current'));app=null;status();}catch(e){$('status').textContent=e.message;}};
(async()=>{try{app=await record('readonly',s=>s.get('current'));if(app){const digest=[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(app.html)))].map(x=>x.toString(16).padStart(2,'0')).join('');if(!APPROVED.includes(digest))throw Error('The saved app could not be verified. Import the original purchased file again.');}if('serviceWorker'in navigator){const registration=await navigator.serviceWorker.register('./sw.js');if(!registration.active)await new Promise(resolve=>{const w=registration.installing||registration.waiting;if(!w)return resolve();w.addEventListener('statechange',()=>{if(w.state==='activated')resolve();});});const cache=await caches.open('oz-launcher-web-3-2db9b94c06ad');shellReady=!!await cache.match(new URL('./index.html',location.href).href);}status();if(app)openApp();}catch(e){$('status').textContent=e.message;}})();
