/* Explicit local saving; scoped separately from the advertising worker. */
(async()=>{
'use strict';const version='2026-10-02.2',cacheName='oz-offline-'+version;
const status=document.querySelector('#offline-status'),list=document.querySelector('#offline-list'),article=document.querySelector('#offline-article'),input=document.querySelector('#offline-query');let data;
const say=t=>{status.textContent=t;};const node=(tag,text)=>{const n=document.createElement(tag);n.textContent=text;return n;};
function render(){list.replaceChildren();if(!data)return;const q=input.value.toLowerCase().trim();for(const g of data.guides.filter(g=>!q||[g.title,...g.aliases].join(' ').toLowerCase().includes(q))){const b=node('button',g.title);b.type='button';b.className='offline-guide';b.addEventListener('click',()=>open(g));list.append(b);}}
function open(g){article.replaceChildren();const h=node('h2',g.title);h.tabIndex=-1;article.append(h,node('p','Content edition '+g.updated+' · '+g.scope));const quick=node('section','');quick.className='quick-answer';quick.append(node('h3','Quick answer'),node('p',g.tldr));article.append(quick,node('h3','Do now'));const ol=node('ol','');for(const [title,body] of g.steps){const li=node('li','');li.append(node('h4',title),node('p',body));ol.append(li);}article.append(ol);for(const [title,key] of [['If help is unavailable','without_help'],['People & practical needs','household'],['Keep essentials within reach','pack_now'],['Next steps','next'],['Watch for','watch']])article.append(node('h3',title),node('p',g[key]));for(const [title,body] of [...g.decisions,...g.faqs])article.append(node('h3',title),node('p',body));article.append(node('h3','Sources & context'),node('p','Source-linked editorial guidance; not independent clinical or specialist certification. External references require a connection.'));for(const [label,url] of g.references){const p=node('p',''),a=node('a',label);a.href=url;a.rel='noopener noreferrer';a.target='_blank';p.append(a);article.append(p);}h.focus();}
async function load(){try{const r=await fetch('/offline/guides.json',{cache:'no-cache'});if(!r.ok)throw Error();data=await r.json();}catch{const r=await caches.match('/offline/guides.json');if(r)data=await r.json();else{say('No saved library is available. Reconnect and choose Save for offline.');return;}}render();const saved=await caches.has(cacheName);say((saved?'Saved on this browser. ':'Not yet saved. ')+data.guides.length+' guides · Edition '+data.updated+'. Saved guides are not live alerts.');}
input.addEventListener('input',render);
document.querySelector('#offline-save').addEventListener('click',async()=>{const b=document.querySelector('#offline-save');b.disabled=true;say('Saving reader, fonts and complete guide text…');try{if(!('serviceWorker'in navigator)||!('caches'in window))throw Error();const reg=await navigator.serviceWorker.register('/offline/sw.js',{scope:'/offline/'});if(!reg.active)await new Promise((resolve,reject)=>{const worker=reg.installing||reg.waiting;if(!worker){resolve();return;}worker.addEventListener('statechange',()=>{if(worker.state==='activated')resolve();if(worker.state==='redundant')reject(Error());});});const c=await caches.open(cacheName);await c.addAll(['/offline/','/offline/reader.js','/offline/guides.json','/styles.css?v=oz10','/app.js?v=oz10','/Assets/site.webmanifest','/Assets/favicon-192x192.png','/Assets/android-chrome-512x512.png','/Assets/oz-mark.webp',...['DMSans-400','DMSans-600','DMSans-700','SpaceGrotesk-400','SpaceGrotesk-600','SpaceGrotesk-700','IBMPlexMono-400'].map(f=>'/Assets/fonts/'+f+'.woff2')]);await load();say('Saved: '+data.guides.length+' complete guides and reader fonts. Bookmark this page and test reopening before relying on it. Browser storage may be removed by the browser.');}catch{await caches.delete(cacheName);say('Saving could not finish. Check free space or browser support, then retry. Download the portable ZIP or PDF packs as an alternative.');}finally{b.disabled=false;}});
document.querySelector('#offline-remove').addEventListener('click',async()=>{for(const k of await caches.keys())if(k.startsWith('oz-offline-'))await caches.delete(k);const r=await navigator.serviceWorker?.getRegistration('/offline/');if(r?.scope.endsWith('/offline/'))await r.unregister();say('Saved reader removed from this browser. Downloaded files remain on the device.');});await load();
})();
