#!/usr/bin/env python3
"""Build the static, answer-first emergency library from one editorial source."""
from html import escape
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCES = {
    "power": [("CDC · Protect yourself during a power outage", "https://www.cdc.gov/natural-disasters/response/what-to-do-protect-yourself-during-a-power-outage.html"), ("CDC · Avoid carbon monoxide poisoning", "https://www.cdc.gov/natural-disasters/psa-toolkit/avoiding-carbon-monoxide-poisoning.html")],
    "weather": [("National Weather Service · Tornado safety", "https://www.weather.gov/safety/tornado-during"), ("National Weather Service · Weather safety", "https://www.weather.gov/safety/")],
    "wildfire": [("CDC · Wildfire smoke and your health", "https://www.cdc.gov/wildfires/about/index.html"), ("AirNow · Fire and smoke map", "https://fire.airnow.gov/")],
    "flood": [("Ready.gov · Floods", "https://www.ready.gov/floods"), ("CDC · Floodwater safety", "https://www.cdc.gov/floods/about/index.html")],
    "evacuation": [("Ready.gov · Evacuation", "https://www.ready.gov/evacuation"), ("Ready.gov · Make a plan", "https://www.ready.gov/plan")],
    "water": [("CDC · Drinking water advisories", "https://www.cdc.gov/water-emergency/about/drinking-water-advisories-an-overview.html"), ("CDC · Make water safe in an emergency", "https://www.cdc.gov/water-emergency/about/index.html")],
    "conflict": [("ICRC · Explosive remnants of war", "https://www.icrc.org/en/law-and-policy/explosive-remnants-war"), ("U.S. State Department · Crisis response", "https://travel.state.gov/en/international-travel/help-abroad/crisis-response.html")],
    "unrest": [("U.S. State Department · Global events and travel", "https://travel.state.gov/en/international-travel/travel-advisories/global-events.html"), ("Ready.gov · Emergency alerts", "https://www.ready.gov/alerts")],
    "nuclear": [("CDC · Radiation emergencies", "https://www.cdc.gov/radiation-emergencies/index.html"), ("CDC · Get inside", "https://www.cdc.gov/radiation-emergencies/response/get-inside.html"), ("CDC · Stay inside", "https://www.cdc.gov/radiation-emergencies/response/stay-inside.html"), ("EPA · Radiation emergency preparedness", "https://www.epa.gov/radtown/radiation-emergency-preparedness-and-response")],
    "restrictions": [("Constitution Annotated · Martial law generally", "https://constitution.congress.gov/browse/essay/artII-S2-C1-1-14/ALDE_00013476/"), ("Ready.gov · Emergency alerts", "https://www.ready.gov/alerts"), ("U.S. State Department · Crisis response", "https://travel.state.gov/en/international-travel/help-abroad/crisis-response.html")],
}

GUIDES = [
  dict(slug="power-outage", title="Power outage", label="UTILITIES", deck="Protect people, preserve essentials, and avoid the hidden hazards of a blackout.",
    tldr="Check the utility and local alerts, then deal with immediate medical, temperature, and water needs. Use battery light and conserve phone power. Run generators and other fuel-burning equipment outdoors, away from windows and vents; never use an oven or grill to heat a home.",
    steps=[("Check the situation", "Find the outage map and local emergency alerts. If someone depends on powered medical equipment, use the backup plan and seek urgent help if that equipment cannot run."), ("Make the space safe", "Use flashlights rather than candles. Keep refrigerators and freezers closed. Unplug sensitive electronics if power is unstable, and leave one light on to show when service returns."), ("Keep air safe", "A generator, camp stove, grill, or vehicle can produce deadly carbon monoxide. Keep fuel-burning equipment outside and well away from openings; use a battery-powered CO alarm if available."), ("Check your people", "Contact neighbors who may need help. Conserve phone power, use text when calls are congested, and monitor official updates.")],
    next="If the outage continues, plan for safe temperature, water, medication refrigeration, and a place to relocate if the home becomes unsafe. Check current food-safety advice before eating perishables after a prolonged outage.",
    watch="Headache, dizziness, weakness, nausea, or confusion near fuel-burning equipment can signal carbon monoxide exposure. Get into fresh air and call emergency services. Never enter a flooded area to operate electrical equipment.", sources="power"),
  dict(slug="severe-weather", title="Severe weather", label="WEATHER", deck="Read the specific warning. The right shelter depends on the hazard.",
    tldr="Identify the warning for your exact location and act on it now. For a tornado warning, go to a basement or a small interior room on the lowest level, away from windows, and protect your head. For flood danger, move to higher ground and do not enter water. Different hazards require different shelter choices.",
    steps=[("Read the warning", "Use local alerts, the National Weather Service, or a weather radio. Check the hazard, affected area, timing, and the action given."), ("Choose shelter for the threat", "For tornadoes, move to the lowest interior space in a sturdy building. For flooding, move away from low ground and use the flooding guide. For lightning, go indoors and stay away from windows and plumbing."), ("Bring the essentials", "Take shoes, a flashlight, phone, charged battery, medication, and the people and pets with you. Do not delay sheltering to collect a full kit."), ("Wait for the all-clear", "A lull does not mean danger is over. Recheck official messages before traveling or inspecting damage.")],
    next="After the warning, avoid downed lines, unstable structures, and flooded roads. Check on others when safe. Review your shelter location and alert settings before the next event.",
    watch="A watch means conditions are possible; a warning means the threat is occurring or imminent in the warned area. Do not use a single generic storm plan for tornado, flood, heat, and winter weather.", sources="weather"),
  dict(slug="wildfire-smoke", title="Wildfire & smoke", label="FIRE / AIR", deck="Separate an approaching fire from a smoke exposure problem.",
    tldr="If your area is ordered to evacuate, leave by the official route as soon as it is safe. If the concern is smoke without a fire threat, stay indoors, close outside-air openings, run filtered recirculated air if available, and watch local air-quality and fire updates. Do not wait for smoke to become visible before checking alerts.",
    steps=[("Know which problem you face", "Check official fire, evacuation, and air-quality notices for your address. An evacuation order changes the decision immediately."), ("If leaving, leave early", "Take people, pets, medication, keys, and essentials; tell a contact where you are going. Use the evacuation guide and current route instructions."), ("If sheltering from smoke", "Close windows and doors. Set HVAC to recirculate where possible, use a portable air cleaner or a cleaner indoor room, and avoid adding indoor smoke from candles, frying, or smoking."), ("Limit outside exposure", "If you must go outside in smoke, a well-fitting N95 or P100 respirator can reduce particle exposure; ordinary cloth masks do not provide the same protection.")],
    next="Keep checking changing wind, fire perimeter, and air-quality conditions. People with heart or lung disease, children, older adults, and pregnant people may need added precautions or clinical advice.",
    watch="If fire threatens the building or officials order departure, indoor smoke control is no substitute for evacuation. If breathing becomes difficult or symptoms are severe, seek urgent medical help.", sources="wildfire"),
  dict(slug="flooding", title="Flooding", label="FLOOD", deck="Distance from floodwater is the first safety decision.",
    tldr="Move to higher ground if water is rising or a flash-flood warning affects you. Never walk, swim, or drive through floodwater; depth, current, contamination, and road damage are hard to judge. Follow evacuation orders and avoid basements or low areas that can fill rapidly.",
    steps=[("Get above the water", "Leave low ground and move to a safe higher location. If a road is flooded, turn around and choose another route."), ("Read the local notice", "Check alerts, road closures, and evacuation instructions. Do not rely on the road being open because it was open earlier."), ("Keep away from hazards", "Floodwater may hide energized wires, debris, sewage, chemicals, and missing road surface. Keep children and pets away."), ("If trapped, call for help", "Give your precise location to emergency services. Move to a higher level if possible; avoid entering a closed attic where you could become trapped by rising water.")],
    next="Return only when officials say it is safe. Photograph damage without entering unstable structures, use protective gear for cleanup, and check the water supply for advisories.",
    watch="Flooding can begin far from the heaviest rain. Do not attempt to cross flowing water to reach a vehicle, home, or belongings.", sources="flood"),
  dict(slug="evacuation", title="Evacuation", label="MOVEMENT", deck="A departure is easier when the destination and route are already decided.",
    tldr="Follow the evacuation order for your area. Leave early enough to use a safe route; take people, pets, medication, identification, phone and charger, keys, and a few essentials. Know where you are going, tell a contact, and do not take a closed or flooded road.",
    steps=[("Confirm the order", "Check the official zone, deadline, route, shelter options, and whether the order includes your address."), ("Gather people first", "Account for everyone and pets. Take required medication and medical supplies, documents, accessible equipment, keys, and a charged phone. Do not spend critical time packing extras."), ("Choose a destination", "Go to a trusted contact or designated shelter outside the hazard area. Check pet rules, accessibility, and transport needs."), ("Leave and report safely", "Use current official routes. Share your destination with an out-of-area contact, keep fuel in the vehicle if relevant, and do not return until authorities say it is safe.")],
    next="Make two destinations and more than one route in advance. Keep a small grab list by the door, especially for medications, pets, and items that cannot be prepacked.",
    watch="If a route is unsafe, do not force it. Follow current local instructions or contact emergency services for help. Some hazards, especially radiation fallout, can make immediate travel more dangerous than sheltering; follow the hazard-specific order.", sources="evacuation", diagram="evacuation"),
  dict(slug="water-disruption", title="Water disruption", label="WATER", deck="Read the exact notice before treating or using tap water.",
    tldr="Find the current water advisory for your address and follow its exact wording. A boil-water advisory, do-not-drink notice, and do-not-use notice require different actions. Boiling can kill germs, but it does not remove chemical contamination. Use sealed bottled or otherwise approved water until the utility or health authority clears the notice.",
    steps=[("Identify the notice", "Find the utility or health department notice for your address, its start time, reason, and permitted uses. Save a screenshot in case service fails."), ("Match use to the instruction", "A boil-water notice generally addresses microbes; follow the authority's boil directions. If the notice says do not drink or do not use, follow those stricter limits and the specified alternative-water instructions."), ("Protect priority needs", "Set aside approved water for drinking, infant formula, medications, tooth brushing, food preparation, and pets, as the notice directs."), ("Wait for clearance", "Do not assume that water is safe because it looks clear or service has returned. Follow flushing or filter replacement instructions after an official all-clear.")],
    next="Store water and a printed copy of your utility's alert channel. Know whether anyone in the household needs extra water or cannot use a typical treatment method.",
    watch="Do not boil water suspected of chemical or fuel contamination. Boiling can concentrate some contaminants; use the alternative source named in the notice.", sources="water", diagram="water"),
  dict(slug="armed-conflict", title="Armed conflict", label="CIVILIAN SAFETY", deck="A civilian plan for shelter, communication, displacement, and unexploded hazards.",
    tldr="If fighting is nearby, get away from windows and exposed areas and follow trustworthy local shelter or evacuation instructions. Keep people together, identify a safe place and a contact outside the area, and carry essential medication and documents if you must leave. Never touch an unfamiliar munition or suspicious debris.",
    steps=[("Get to safer cover", "Move away from windows and exterior openings to a sturdy interior space when travel is unsafe. If authorities direct an evacuation and the route is safe, follow it."), ("Keep a family plan", "Agree on a meeting point and an out-of-area contact. Write down important numbers; phone and data service may fail."), ("Prepare for movement", "Keep identification, medication, water, phone power, weather-appropriate clothing, and children’s essentials accessible. Check current routes and shelter options before departure."), ("Avoid explosive remnants", "Do not approach, handle, or move unexploded objects. Keep others away and report the location through local authorities when safe.")],
    next="If abroad, check your country's embassy or consular crisis messages; do not assume transport or evacuation will be provided. Reassess each movement against current conditions rather than an old map or rumor.",
    watch="This is civilian protective guidance, not a movement order. The safest choice can change quickly with the location, time, and instructions from responsible authorities.", sources="conflict"),
  dict(slug="civil-unrest", title="Civil unrest", label="PUBLIC SAFETY", deck="Move away from active violence and keep your route decisions grounded in current information.",
    tldr="If violence or dangerous crowd movement is near you, leave the immediate area by a safe route or shelter in a secure place if travel is unsafe. Check local alerts, road closures, and transit changes. Avoid confrontation and keep a way to contact the people you need to reach.",
    steps=[("Separate the event from your location", "Check what is happening on your route, not just citywide headlines. Peaceful assembly and a nearby dangerous incident are different conditions."), ("Choose a safe path", "Move away from active violence and blocked roads. If there is no safe exit, shelter inside, away from windows, and update a trusted contact."), ("Stay informed", "Use official local notices for curfews, transport changes, and emergency services, and verify unconfirmed social posts before acting."), ("Regroup deliberately", "Arrange a meeting point and a backup contact if mobile networks are strained. Wait for reliable updates before returning to a disrupted area.")],
    next="Before going out, check whether your route crosses a closure and identify an alternative. Carry basic identification, necessary medication, and phone power.",
    watch="Do not assume a protest is violent or that a citywide alert applies equally to every neighborhood. If an order applies, read its location, hours, and exceptions.", sources="unrest"),
  dict(slug="nuclear-detonation", title="Nuclear detonation", label="RADIATION", deck="Get inside, stay inside, and get reliable instructions.",
    tldr="After a nuclear detonation, get inside the nearest sturdy building as quickly as you can. Move to a basement or central interior area, away from walls, windows, and the roof. Stay inside and tune to official updates; the first 24 hours are especially important unless the building is unsafe or authorities direct you elsewhere.",
    steps=[("Get inside", "Do not remain outdoors looking at the blast or travel across town for a preferred shelter. A substantial building offers better protection than a vehicle or open space."), ("Go deeper inside", "Use a basement or the middle of the building with as much material between you and outdoors as possible. Close doors and windows."), ("If exposed outdoors, clean up", "Once sheltered, remove the outer layer of clothing and set it aside away from people; wash exposed skin with water and soap when available. This reduces contamination brought indoors."), ("Stay tuned", "Use radio, phone, or other available channels for location-specific instructions. Avoid going out to collect family members who are already sheltered elsewhere.")],
    next="Arrange water, medications, and a way to receive alerts within the shelter. Leave only for an immediate threat such as fire, collapse, or other life-threatening condition, or when officials direct a safe move.",
    watch="Fallout conditions vary by place and time. Do not treat a fixed distance or a clock as an all-clear; use the official instructions for your location. Potassium iodide is not a general radiation antidote and should be taken only when public-health officials advise it.", sources="nuclear", diagram="nuclear"),
  dict(slug="emergency-restrictions", title="Emergency restrictions & martial law", label="CIVIC CONDITIONS", deck="Find the actual order. Work from its words, place, and time.",
    tldr="If officials announce a curfew, movement restriction, state of emergency, or martial law, find the actual order from the authority that issued it. Check the affected area, start and end times, permitted travel, essential-service exceptions, and how updates will be announced. Keep identification and necessary medical information accessible, and seek qualified local legal help for a rights or detention question.",
    steps=[("Verify the announcement", "Read the original order or official alert rather than a repost. Confirm the issuing authority, jurisdiction, and effective time."), ("Map the practical effect", "Note what movement or services are restricted, who is exempt, and where to obtain food, medication, medical care, and shelter."), ("Plan essential movement", "Carry identification and relevant documentation, tell a contact your route, and use current official information about closures and checkpoints. Avoid unnecessary travel into a restricted area."), ("Keep records and reassess", "Save the order, updates, and emergency contacts offline if possible. If you are detained or need advice about your rights, contact a qualified attorney or local legal aid.")],
    next="A declaration of emergency, a curfew, and martial law are distinct legal actions. Their meaning and lawful scope depend on the jurisdiction and the actual instrument issued; this guide cannot determine the law for a specific place.",
    watch="Do not infer blanket rules from the phrase “martial law” in a headline. Follow live safety instructions, and verify any claim about suspended rights or universal powers against the actual order and local legal advice.", sources="restrictions"),
]

def diagram(kind):
    if kind == "nuclear":
        return '''<figure class="guide-figure"><svg viewBox="0 0 680 210" role="img" aria-labelledby="shelter-title shelter-desc"><title id="shelter-title">Where to shelter in a sturdy building</title><desc id="shelter-desc">A building outline surrounds a highlighted interior space, away from windows, exterior walls, and roof.</desc><rect x="48" y="24" width="584" height="155" fill="#1d2023" stroke="#777e7d" stroke-width="3"/><path d="M48 24h584M48 179h584" stroke="#777e7d" stroke-width="8"/><path d="M95 24v155m490-155v155" stroke="#6b7378" stroke-width="3" stroke-dasharray="9 8"/><rect x="213" y="75" width="254" height="85" fill="#31312e" stroke="#f05a2a" stroke-width="3"/><text x="340" y="112" text-anchor="middle" fill="#f2eee6" font-size="17">INTERIOR / BASEMENT</text><text x="340" y="138" text-anchor="middle" fill="#d7d1c4" font-size="13">MORE MATERIAL BETWEEN YOU AND OUTSIDE</text><text x="340" y="202" text-anchor="middle" fill="#a7aba9" font-size="12">STAY AWAY FROM WINDOWS, EXTERIOR WALLS, AND ROOF</text></svg><figcaption>Conceptual shelter location; use the actual building and official instructions.</figcaption></figure>'''
    if kind == "water":
        return '''<figure class="guide-figure"><figcaption class="figure-heading">Read the advisory before using the tap.</figcaption><div class="decision-grid"><div><b>BOIL WATER</b><span>Follow the notice’s boil instructions for microbial risk.</span></div><div><b>DO NOT DRINK</b><span>Use the approved alternative for drinking and food.</span></div><div><b>DO NOT USE</b><span>Avoid the uses named in the notice; follow the authority’s alternative-water directions.</span></div></div><figcaption>These labels are a reading aid. The exact local notice controls.</figcaption></figure>'''
    if kind == "evacuation":
        return '''<figure class="guide-figure"><figcaption class="figure-heading">The departure sequence</figcaption><div class="decision-grid"><div><b>01 / ORDER</b><span>Confirm your zone and instructions.</span></div><div><b>02 / PEOPLE</b><span>Account for people, pets, and essential medicine.</span></div><div><b>03 / ROUTE</b><span>Check a safe route and destination before leaving.</span></div></div><figcaption>Do not delay departure for a perfect bag when an order requires immediate movement.</figcaption></figure>'''
    return ""

def build():
    shell = (ROOT / "emergencies/index.html").read_text()
    before_main = shell[:shell.index('  <main id="main"')]
    after_main = shell[shell.index('  <footer class="site-footer"'):]
    for n, guide in enumerate(GUIDES, 1):
        title = escape(guide["title"])
        header = before_main.replace('content="Ten original, answer-first Osprey Zero guides for emergencies, from outages and floods to conflict, unrest, and radiation."', f'content="{escape(guide["deck"], quote=True)}"')
        header = header.replace('https://ospreyzero.com/emergencies/', f'https://ospreyzero.com/emergencies/{guide["slug"]}/')
        header = header.replace('<title>Emergency directory — Osprey Zero</title>', f'<title>{title} guide — Osprey Zero</title>')
        steps = ''.join(f'<li><span class="step-num">{i:02d}</span><div><h3>{escape(h)}</h3><p>{escape(p)}</p></div></li>' for i, (h,p) in enumerate(guide['steps'],1))
        sources = ''.join(f'<li><a href="{escape(url, quote=True)}" target="_blank" rel="noopener noreferrer">{escape(label)} <span aria-hidden="true">↗</span></a></li>' for label,url in SOURCES[guide['sources']])
        related_slugs = {
            'power-outage':['water-disruption','severe-weather','evacuation'], 'severe-weather':['flooding','power-outage','evacuation'],
            'wildfire-smoke':['evacuation','water-disruption','severe-weather'], 'flooding':['evacuation','water-disruption','severe-weather'],
            'evacuation':['wildfire-smoke','flooding','armed-conflict'], 'water-disruption':['power-outage','flooding','evacuation'],
            'armed-conflict':['evacuation','civil-unrest','emergency-restrictions'], 'civil-unrest':['emergency-restrictions','evacuation','armed-conflict'],
            'nuclear-detonation':['evacuation','water-disruption','power-outage'], 'emergency-restrictions':['civil-unrest','evacuation','armed-conflict']
        }[guide['slug']]
        related = [next(g for g in GUIDES if g['slug'] == slug) for slug in related_slugs]
        links = ''.join(f'<a href="/emergencies/{g["slug"]}/">{escape(g["title"])} <span aria-hidden="true">↗</span></a>' for g in related)
        page = f'''  <main id="main" class="subpage guide-page">
    <div class="wrap guide-breadcrumb"><a href="/emergencies/">Emergency directory</a><span aria-hidden="true">/</span><span>{title}</span></div>
    <article class="wrap guide-layout">
      <div class="guide-main">
        <header class="guide-heading"><p class="kicker"><span class="accent-line"></span> OZ FIELD GUIDE / {n:02d} / {escape(guide['label'])}</p><h1>{title}</h1><p class="guide-deck">{escape(guide['deck'])}</p><div class="guide-meta"><span>UPDATED 02 OCT 2026</span><span>ABOUT 3 MIN READ</span><button type="button" class="print-link" data-print>Print guide ↗</button></div></header>
        <section class="quick-answer" aria-labelledby="quick-title"><p class="quick-label" id="quick-title">THE QUICK ANSWER</p><p>{escape(guide['tldr'])}</p></section>
        <div class="guide-alert"><span aria-hidden="true">!</span><p>In immediate danger, contact local emergency services. Current instructions for your location take priority.</p></div>
        <section class="guide-section" id="do-now"><p class="kicker"><span class="accent-line"></span> 01 / DO NOW</p><h2>First moves.</h2><ol class="action-list">{steps}</ol></section>
        {diagram(guide.get('diagram'))}
        <section class="guide-section" id="next"><p class="kicker"><span class="accent-line"></span> 02 / NEXT</p><h2>When the first minute is over.</h2><p>{escape(guide['next'])}</p></section>
        <section class="guide-section guide-caution" id="watch"><p class="kicker"><span class="accent-line"></span> 03 / WATCH FOR</p><h2>The exception that matters.</h2><p>{escape(guide['watch'])}</p></section>
        <section class="guide-section guide-sources" id="sources"><p class="kicker"><span class="accent-line"></span> 04 / VERIFY</p><h2>Sources & context.</h2><p>Osprey Zero wrote this guide from the references below. It is a general starting point, not a live alert. Check the issuing authority for your area; guidance and conditions can change.</p><ul>{sources}</ul><small>Guide updated 02 October 2026. U.S.-based references unless noted; follow authorities where you are.</small></section>
      </div>
      <aside class="guide-rail" aria-label="Guide contents"><div class="rail-panel"><span>IN THIS GUIDE</span><a href="#do-now">01 / Do now</a><a href="#next">02 / Next</a><a href="#watch">03 / Watch for</a><a href="#sources">04 / Sources</a><div class="rail-rule"></div><a href="/emergencies/">← All situations</a></div></aside>
    </article>
    <section class="wrap guide-end"><div><p class="kicker"><span class="accent-line"></span> KEEP EXPLORING</p><h2>Other situations.</h2></div><div class="related-links">{links}</div></section>
  </main>
'''
        out = ROOT / 'emergencies' / guide['slug'] / 'index.html'
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text((header + page + after_main).replace('/styles.css?v=oz4','/styles.css?v=oz5').replace('/app.js?v=oz3','/app.js?v=oz4'))

if __name__ == '__main__':
    build()
