"""Build the approved homepage from public guide and product metadata."""
import json,re
from pathlib import Path
from html import escape as e
from decimal import Decimal
from toolkit_catalog import load_catalog,product_route
R=Path(__file__).resolve().parents[1]
guides=[json.loads(p.read_text()) for p in (R/'content/guides').glob('*.json')]
categories=json.loads((R/'content/taxonomy.json').read_text())
catalog=load_catalog(R);topics=[p for p in catalog['products'] if p['kind']=='topic' and p['status']!='retired']
benefits={'power-outage':'Plan lighting, protect food and organize your household through a blackout.','water-disruption':'Organize safe water reserves, understand notices and plan household hygiene.','emergency-food':'Build a usable pantry with no-cook meals, shopping lists and a rotation plan.','evacuation':'Choose destinations, prepare carryable bags and coordinate transport and check-ins.'}
cards=''
for p in topics:
 ready=p['status']=='ready';complete=p['status']=='files-ready'
 status='Available now' if ready else 'Checkout opening soon' if complete else 'In development'
 price=f' · ${Decimal(str(p["price"])):.2f}' if ready else ''
 image=f'<div class="home-kit-preview"><img src="/Assets/toolkit-previews/{p["slug"]}.webp" alt="Actual cover of the {e(p["title"])} guide" width="602" height="850" loading="lazy" decoding="async"><span>ACTUAL GUIDE COVER</span></div>' if (R/f'Assets/toolkit-previews/{p["slug"]}.webp').is_file() else ''
 link=('<a class="button button-primary" data-payhip-checkout href="'+e(p['checkout_url'],quote=True)+'">Buy toolkit'+price+'</a>') if ready else f'<a class="text-link" href="{product_route(p)}">View toolkit <span aria-hidden="true">→</span></a>'
 cards+=f'<article class="home-kit-card">{image}<div class="home-kit-copy"><p class="home-kit-status">{status}</p><h3><a href="{product_route(p)}">{e(p["title"])}</a></h3><p>{e(benefits.get(p["slug"],p["summary"]))}</p>{link}</div></article>'
subjects=''.join(f'<a href="/library/{c["id"]}/"><span>{e(c["title"])}</span><small>{sum(g["category"]==c["id"] for g in guides)} {"guide" if sum(g["category"]==c["id"] for g in guides)==1 else "guides"} <span aria-hidden="true">↗</span></small></a>' for c in categories)
quick=[('Power outage','/emergencies/power-outage/','Lighting, food and safe backup power'),('Unsafe water','/emergencies/water-disruption/','Read the notice and choose safe water'),('Severe weather','/emergencies/severe-weather/','Choose the specific hazard'),('Evacuation','/emergencies/evacuation/','Leave with a destination and a plan'),('Home fire','/emergencies/home-fire/','Get out and stay out'),('First aid','/library/medical/','Find the response for the situation')]
quicklinks=''.join(f'<a class="home-situation" href="{url}"><strong>{e(title)}</strong><span>{e(desc)}</span><b aria-hidden="true">↗</b></a>' for title,url,desc in quick)
main=f'''<main id="main" class="home-page">
<section class="wrap home-hero" aria-labelledby="hero-title"><p class="kicker">FREE KNOWLEDGE / PRACTICAL PREPARATION</p><h1 id="hero-title">Be ready<br><span>before you need to be.</span></h1><p class="home-lede">Free emergency guidance and practical tools to help you protect your household, prepare your supplies and make a workable plan.</p>
<div class="finder-bar home-finder"><label for="emergency-search">Search {len(guides)} free guides</label><div class="search-control"><span aria-hidden="true">⌕</span><input id="emergency-search" type="search" placeholder="Power outages, water safety, evacuation, radios…" autocomplete="off" aria-controls="home-search-results"><kbd>/</kbd></div><span class="finder-count" id="finder-count" role="status" aria-live="polite" aria-atomic="true">No signup needed · Quick answers first</span></div><div id="home-search-results" class="search-results" hidden></div>
<div class="hero-urgent" aria-label="Urgent situations"><span>Need a first step now?</span><a href="/emergencies/cpr/">Not breathing</a><a href="/emergencies/choking/">Choking</a><a href="/emergencies/gas-leak/">Smell gas</a><a href="/emergencies/home-fire/">Fire</a></div><noscript><p>Search needs JavaScript. <a href="/library/">Browse all free guides</a>.</p></noscript>
<div class="home-hero-actions"><a class="button button-primary" href="/library/">Browse free guides <span aria-hidden="true">→</span></a><a class="button button-outline" href="#guide-access">Explore the toolkits <span aria-hidden="true">↓</span></a></div><p class="home-signature">Skill beats panic. Every time.</p></section>
<section class="wrap home-common" id="find-help" aria-labelledby="common-title"><div class="home-section-heading"><div><p class="kicker">A CLEAR NEXT STEP</p><h2 id="common-title">Start with what’s happening.</h2></div><a class="text-link" href="/emergencies/">All emergency guides →</a></div><div class="topic-grid home-situation-grid" id="topic-grid">{quicklinks}</div><p class="home-safety-note">Act on immediate danger. Seek qualified help when reachable and safe; do not wait for a response to take the first protective step.</p></section>
<section class="wrap home-toolkits" id="guide-access" aria-labelledby="access-title"><div class="home-section-heading"><div><p class="kicker">OSPREY ZERO / PREPARATION TOOLKITS</p><h2 id="access-title">Turn knowledge<br><span>into a plan you can use.</span></h2></div><p>Branded guides, checklists, shopping lists, contact cards and Excel calculators. Organized into A4 and US Letter editions.</p></div><div class="home-kit-grid">{cards}</div><div class="home-kit-footer"><p>Free guidance stays free. Toolkits bring the printable resources and planning tools together.</p><a class="text-link" href="/toolkits/">Explore all toolkits →</a></div></section>
<section class="home-start-band"><div class="wrap home-start" aria-labelledby="start-title"><div class="home-section-heading"><div><p class="kicker">NEW TO PREPAREDNESS?</p><h2 id="start-title">Start small. Build confidence.</h2></div><p>You don’t need to buy everything at once. Begin with your people, your essentials and a plan you can actually use.</p></div><ol class="home-start-grid"><li><span>STEP 1</span><h3>Make your household plan.</h3><p>Choose contacts, meeting points and what would make you stay or leave.</p><a class="text-link" href="/preparedness/household-emergency-plan/">Build your plan →</a></li><li><span>STEP 2</span><h3>Secure the essentials.</h3><p>Prioritize water, food, lighting and care needs around your budget.</p><a class="text-link" href="/preparedness/budget-preparedness/">Prepare on a budget →</a></li><li><span>STEP 3</span><h3>Practice and maintain.</h3><p>Test the plan, check your supplies and fix one useful gap at a time.</p><a class="text-link" href="/preparedness/preparedness-maintenance/">Keep it ready →</a></li></ol></div></section>
<section class="wrap home-encyclopedia" aria-labelledby="encyclopedia-title"><div class="home-section-heading"><div><p class="kicker">{len(guides)} FREE GUIDES / {len(categories)} SUBJECTS</p><h2 id="encyclopedia-title">Explore what matters to you.</h2></div><a class="text-link" href="/topics/">Every topic A–Z →</a></div><div class="home-subject-grid">{subjects}</div><div class="home-trust-strip"><span>Quick answers</span><span>Practical steps</span><span>Linked sources</span><a href="/resources/">Explore the references ↗</a></div></section>
<section class="wrap home-planner" aria-labelledby="planner-title"><div><p class="kicker">HOUSEHOLD PLANNER / SEPARATE PRODUCT</p><h2 id="planner-title">Your household.<br><span>One clear plan.</span></h2><p>Manage supplies, contacts, budgets and tasks in one practical dashboard. Spot gaps, plan your next purchase and keep your household information organized.</p><div class="home-planner-actions"><a class="button button-outline" href="/planner/">Explore the planner →</a><a class="text-link" href="/planner/app/">Already own it? Open the app ↗</a></div><p class="home-planner-note">Separate from the toolkits. Customers import their purchased app file; records stay in their browser. No account or cloud sync. New purchases open after checkout is verified.</p></div><div class="home-planner-features" aria-label="Planner features"><div><span>SUPPLIES</span><h3>Know what you have.</h3><p>Water, food, inventory and shopping priorities.</p></div><div><span>PEOPLE</span><h3>Keep the plan together.</h3><p>Contacts, household needs and printable plans.</p></div><div><span>UPKEEP</span><h3>See what needs attention.</h3><p>Budgets, tasks, maintenance and editable backups.</p></div></div></section>
<section class="home-mission-band"><div class="wrap home-mission"><div><p class="kicker">OUR MISSION</p><h2>Preparedness within reach.</h2><p>Osprey Zero was founded by Michael LaChance in Florida to put useful knowledge, resources and tools in the hands of everyday people—before they need them. Our encyclopedia is free to read, and our toolkits help turn that knowledge into practical household preparation.</p><a class="text-link" href="/about/">Meet Osprey Zero →</a></div><div class="home-update" id="newsletter"><p class="kicker">FIELD NOTES</p><h3>Follow what’s next.</h3><p>Request updates about new guides and toolkit releases. Email delivery is being set up; free guides never require signup.</p><form data-signup="field-notes-newsletter" name="field-notes-newsletter" method="POST" data-netlify="true" netlify-honeypot="bot-field" action="/thanks/"><input type="hidden" name="form-name" value="field-notes-newsletter"><p class="honeypot"><label>Leave this empty <input name="bot-field"></label></p><label for="newsletter-email">Email address</label><div class="email-row"><input id="newsletter-email" name="email" type="email" placeholder="you@example.com" autocomplete="email" required><button class="button button-ash" type="submit">Request updates →</button></div><p class="form-note"><a href="/privacy/">Privacy & email details</a></p><p class="form-status" data-form-status role="status" aria-live="polite"></p></form></div></div></section>
<section class="wrap home-clipjar"><div><p class="kicker">AN OSPREY ZERO PROJECT</p><h2>Keep our videos close.</h2><p>Use ClipJar to save Osprey Zero videos you have permission to keep for offline viewing.</p></div><a class="button button-outline" href="https://clipjar.io/" target="_blank" rel="noopener noreferrer">Open ClipJar ↗</a></section>
</main>'''
p=R/'index.html';s=p.read_text();s=re.sub(r'<main id="main".*?</main>',lambda _:main,s,flags=re.S)
s=re.sub(r'<meta name="description"[^>]*>','<meta name="description" content="Search free emergency and preparedness guides. Explore Osprey Zero toolkits, household planning tools, checklists and practical resources.">',s)
p.write_text(s)
print(f'Built streamlined homepage: {len(guides)} guides, {len(topics)} topic toolkits, one search.')
