"""Build the approved homepage from public guide and product metadata."""
import json,re
from pathlib import Path
from html import escape as e
from decimal import Decimal
from toolkit_catalog import load_catalog,product_route
from build_briefing import homepage_section
R=Path(__file__).resolve().parents[1]
guides=[json.loads(p.read_text()) for p in (R/'content/guides').glob('*.json')]
categories=json.loads((R/'content/taxonomy.json').read_text())
catalog=load_catalog(R);topics=[p for p in catalog['products'] if p['kind']=='topic' and p['status']!='retired']
benefits={'power-outage':'Plan lighting, protect food and organize your household through a blackout.','water-disruption':'Organize safe water reserves, understand notices and plan household hygiene.','emergency-food':'Build a usable pantry with no-cook meals, shopping lists and a rotation plan.','evacuation':'Choose destinations, prepare carryable bags and coordinate transport and check-ins.'}
cards=''
for p in topics:
 ready=p['status']=='ready';complete=p['status']=='files-ready'
 status='Available now' if ready else 'Checkout opening soon' if complete else 'Redesign underway · Purchases paused'
 price=f' · ${Decimal(str(p["price"])):.2f}' if ready else ''
 link=('<a class="button button-primary" data-payhip-checkout href="'+e(p['checkout_url'],quote=True)+'">Buy toolkit'+price+'</a>') if ready else f'<a class="text-link" href="{product_route(p)}">View toolkit <span aria-hidden="true">→</span></a>'
 cards+=f'<article class="home-kit-card"><div class="home-kit-copy"><p class="home-kit-status">{status}</p><h3><a href="{product_route(p)}">{e(p["title"])}</a></h3><p>{e(benefits.get(p["slug"],p["summary"]))}</p>{link}</div></article>'
subjects=''.join(f'<a href="/library/{c["id"]}/"><span>{e(c["title"])}</span><small>{sum(g["category"]==c["id"] for g in guides)} {"guide" if sum(g["category"]==c["id"] for g in guides)==1 else "guides"} <span aria-hidden="true">↗</span></small></a>' for c in categories)
quick=[('Power outage','/emergencies/power-outage/','Lighting, food and safe backup power'),('Unsafe water','/emergencies/water-disruption/','Read the notice and choose safe water'),('Severe weather','/emergencies/severe-weather/','Choose the specific hazard'),('Evacuation','/emergencies/evacuation/','Leave with a destination and a plan'),('Home fire','/emergencies/home-fire/','Get out and stay out'),('First aid','/library/medical/','Find the response for the situation')]
quicklinks=''.join(f'<a class="home-situation" href="{url}"><strong>{e(title)}</strong><span>{e(desc)}</span><b aria-hidden="true">↗</b></a>' for title,url,desc in quick)
main=f'''<main id="main" class="home-page">
<section class="wrap home-hero field-hero" aria-labelledby="hero-title">
<div class="home-hero-stage"><div class="home-hero-intro"><div class="hero-masthead"><p class="kicker">THE PREPAREDNESS LIBRARY<br><span>CIVILIAN KNOWLEDGE. FREE ACCESS.</span></p><img src="/Assets/oz-mark.webp" alt="" width="52" height="52"></div><div class="hero-editorial-lockup"><h1 id="hero-title"><span>SKILL </span><span>BEATS </span><span class="hero-panic">PANIC.</span></h1><p class="hero-everytime">Every<br>time.</p></div><p class="home-lede">Practical guidance for emergencies and everyday preparedness.</p><div class="finder-bar home-finder"><label for="emergency-search">Search {len(guides)} free guides</label><div class="search-control"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg><input id="emergency-search" type="search" placeholder="What do you need to know?" autocomplete="off" autocorrect="off" autocapitalize="none" spellcheck="false" enterkeyhint="search" aria-controls="home-search-results"></div><span class="finder-count" id="finder-count" role="status" aria-live="polite" aria-atomic="true">No account. No signup. Just useful knowledge.</span></div><div id="home-search-results" class="search-results" hidden></div></div>
</div>
<div class="hero-urgent" aria-label="Urgent situations"><span>Need a first step now?</span><a href="/emergencies/cpr/">Not breathing</a><a href="/emergencies/choking/">Choking</a><a href="/emergencies/gas-leak/">Smell gas</a><a href="/emergencies/home-fire/">Fire</a></div><noscript><p>Search needs JavaScript. <a href="/library/">Browse all free guides</a>.</p></noscript></section>
<section class="wrap home-common" id="find-help" aria-labelledby="common-title"><div class="home-section-heading"><div><p class="kicker">01 / EMERGENCY GUIDES</p><h2 id="common-title">Emergency guides</h2></div><a class="text-link" href="/emergencies/">View all emergency guides →</a></div><div class="topic-grid home-situation-grid" id="topic-grid">{quicklinks}</div><p class="home-safety-note">Act on immediate danger. Seek qualified help when reachable and safe; do not wait for a response to take the first protective step.</p></section>
<section class="wrap home-encyclopedia" aria-labelledby="encyclopedia-title"><div class="home-section-heading"><div><p class="kicker">02 / {len(categories)} SUBJECTS. ONE FIELD MANUAL.</p><h2 id="encyclopedia-title">Explore topics</h2></div><a class="text-link" href="/topics/">Browse topics A–Z →</a></div><div class="home-subject-grid">{subjects}</div><div class="home-trust-strip"><span>Quick answers</span><span>Practical steps</span><span>Linked sources</span><a href="/resources/">Explore the references ↗</a></div></section>
{homepage_section()}
<section class="wrap home-toolkits" id="guide-access" aria-labelledby="access-title"><div class="home-section-heading"><div><p class="kicker">04 / OPTIONAL PLANNING TOOLS</p><h2 id="access-title">Preparation toolkits.</h2></div><p>Our toolkits are being redesigned with more practical guides, checklists and household tools. Purchases are paused while we prepare the new editions.</p></div><div class="home-kit-grid">{cards}</div><div class="home-kit-footer"><p>Free guidance stays free. Toolkits bring the printable resources and planning tools together.</p><a class="text-link" href="/toolkits/">Explore all toolkits →</a></div></section>
<section class="wrap home-planner" aria-labelledby="planner-title"><div><p class="kicker">HOUSEHOLD PLANNER / SEPARATE PRODUCT</p><h2 id="planner-title">Household planner.</h2><p>Organize supplies, contacts, budgets and upkeep in one local dashboard.</p><div class="home-planner-actions"><a class="button button-outline" href="/planner/">Explore the planner →</a><a class="text-link" href="/planner/app/">Already own it? Open the app ↗</a></div><p class="home-planner-note">Separate from the toolkits. Customers import their purchased app file; records stay in their browser. No account or cloud sync. New purchases open after checkout is verified.</p></div></section>
<section class="home-mission-band"><div class="wrap home-mission"><div><p class="kicker">05 / ABOUT OSPREY ZERO</p><h2>About Osprey Zero</h2><p>Osprey Zero was founded by Michael LaChance in Florida to put useful knowledge, resources and tools in the hands of everyday people—before they need them. Our encyclopedia is free to read, and our toolkits help turn that knowledge into practical household preparation.</p><a class="text-link" href="/about/">Meet Osprey Zero →</a></div><div class="home-update" id="newsletter"><p class="kicker">FIELD NOTES</p><h3>Guide and toolkit updates</h3><p>Request updates about new guides and toolkit releases. Email delivery is being set up; free guides never require signup.</p><form data-signup="field-notes-newsletter" name="field-notes-newsletter" method="POST" data-netlify="true" netlify-honeypot="bot-field" action="/thanks/"><input type="hidden" name="form-name" value="field-notes-newsletter"><p class="honeypot"><label>Leave this empty <input name="bot-field"></label></p><label for="newsletter-email">Email address</label><div class="email-row"><input id="newsletter-email" name="email" type="email" placeholder="you@example.com" autocomplete="email" required><button class="button button-ash" type="submit">Request updates →</button></div><p class="form-note"><a href="/privacy/">Privacy & email details</a></p><p class="form-status" data-form-status role="status" aria-live="polite"></p></form></div></div></section>
<section class="wrap home-clipjar"><div><p class="kicker">AN OSPREY ZERO PROJECT</p><h2>Save permitted videos with ClipJar</h2><p>Use ClipJar to save Osprey Zero videos you have permission to keep for offline viewing.</p></div><a class="button button-outline" href="https://clipjar.io/" target="_blank" rel="noopener noreferrer">Open ClipJar ↗</a></section>
</main>'''
p=R/'index.html';s=p.read_text();s=re.sub(r'<main id="main".*?</main>',lambda _:main,s,flags=re.S)
s=re.sub(r'<meta name="description"[^>]*>','<meta name="description" content="Search free emergency and preparedness guides. Explore Osprey Zero toolkits, household planning tools, checklists and practical resources.">',s)
s=re.sub(r'<script src="/field-book.js[^"]*"[^>]*></script>', '', s)

if '/briefing.css?' not in s:s=s.replace('</head>','<link rel="stylesheet" href="/briefing.css?v=oz1"><script src="/briefing.js?v=oz1" defer></script></head>')
p.write_text(s)
print(f'Built streamlined homepage: {len(guides)} guides, {len(topics)} topic toolkits, one search.')
