def diagram(kind):
    if kind == "nuclear":
        return '''<figure class="guide-figure"><svg viewBox="0 0 680 210" role="img" aria-labelledby="shelter-title shelter-desc"><title id="shelter-title">Where to shelter in a sturdy building</title><desc id="shelter-desc">A building outline surrounds a highlighted interior space, away from windows, exterior walls, and roof.</desc><rect x="48" y="24" width="584" height="155" fill="#1d2023" stroke="#777e7d" stroke-width="3"/><path d="M48 24h584M48 179h584" stroke="#777e7d" stroke-width="8"/><path d="M95 24v155m490-155v155" stroke="#6b7378" stroke-width="3" stroke-dasharray="9 8"/><rect x="213" y="75" width="254" height="85" fill="#31312e" stroke="#f05a2a" stroke-width="3"/><text x="340" y="112" text-anchor="middle" fill="#f2eee6" font-size="17">INTERIOR / BASEMENT</text><text x="340" y="138" text-anchor="middle" fill="#d7d1c4" font-size="13">MORE MATERIAL BETWEEN YOU</text><text x="340" y="154" text-anchor="middle" fill="#d7d1c4" font-size="13">AND OUTSIDE</text><text x="340" y="202" text-anchor="middle" fill="#a7aba9" font-size="12">STAY AWAY FROM WINDOWS, EXTERIOR WALLS, AND ROOF</text></svg><figcaption>Conceptual shelter location; use the actual building and official instructions.</figcaption></figure>'''
    if kind == "water":
        return '''<figure class="guide-figure"><figcaption class="figure-heading">Read the advisory before using the tap.</figcaption><div class="decision-grid"><div><b>BOIL WATER</b><span>Follow the notice’s boil instructions for microbial risk.</span></div><div><b>DO NOT DRINK</b><span>Use the approved alternative for drinking and food.</span></div><div><b>DO NOT USE</b><span>Avoid the uses named in the notice; follow the authority’s alternative-water directions.</span></div></div><figcaption>These labels are a reading aid. The exact local notice controls.</figcaption></figure>'''
    if kind == "evacuation":
        return '''<figure class="guide-figure"><figcaption class="figure-heading">The departure sequence</figcaption><div class="decision-grid"><div><b>01 / ORDER</b><span>Confirm your zone and instructions.</span></div><div><b>02 / PEOPLE</b><span>Account for people, pets, and essential medicine.</span></div><div><b>03 / ROUTE</b><span>Check a safe route and destination before leaving.</span></div></div><figcaption>Do not delay departure for a perfect bag when an order requires immediate movement.</figcaption></figure>'''
    return ""

