/* Non-published test fixtures. They are inert schema tests, not source reports. */
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const api=require('../briefing.js');
const code=fs.readFileSync('briefing.js','utf8');
const now=Date.now(), iso=delta=>new Date(now+delta).toISOString();
const record={id:'test-only-record',title:'Test-only inert record',source:{id:'test-source',name:'Test-only source',kind:'official'},category:'weather',url:'https://example.com/source',summary:'Literal <script> text must stay text.',displaySummary:'Literal <script> text must stay text.',instructions:'Test-only source instructions.',location:{scope:'US',label:'Test-only location',codes:['FL']},publishedAt:iso(-3600000),updatedAt:iso(-3600000),lastCheckedAt:iso(-3600000),expiresAt:iso(3600000),status:'current',cardMeaning:'If this situation affects you, review the mapped guides.',whatThisMeans:'Test-only context',preparedness:['Test-only reviewed step'],guides:[{title:'Power outage',url:'/emergencies/power-outage/'},{title:'Household planning',url:'/preparedness/household-emergency-plan/'}],resources:[],updates:[]};
const snapshot={schemaVersion:1,generatedAt:iso(0),lastSuccessfulAt:iso(-3600000),storageStatus:'ok',events:[record],sources:[{id:'test-source',name:'Test-only source',status:'ok',lastSuccessAt:iso(-3600000),lastAttemptAt:iso(-3600000),website:'https://example.com/',coverage:{label:'Test-only coverage',status:'ok'}}]};
assert.equal(api.snapshotState(snapshot,now).state,'current');
assert.equal(api.snapshotState({...snapshot,lastSuccessfulAt:iso(-15*3600000)},now).state,'stale');
assert.equal(api.snapshotState({...snapshot,sources:[{...snapshot.sources[0],lastSuccessAt:iso(-15*3600000)}]},now).state,'partial');
assert.equal(api.snapshotState({...snapshot,sources:[{...snapshot.sources[0],coverage:{status:'partial'}}]},now).state,'partial');
assert.equal(api.snapshotState({...snapshot,storageStatus:'initial-snapshot'},now).state,'partial');
assert.equal(api.snapshotState({...snapshot,sources:[],events:[],lastSuccessfulAt:null},now).state,'unavailable');
assert.match(api.recordState({...record,expiresAt:iso(-1)},now).note,/does not mean the threat has ended/);
assert.match(api.recordState({...record,status:'no-longer-listed'},now).note,/not an all-clear/);
assert.match(api.recordState({...record,status:'cancelled'},now).note,/does not establish current safety/);
assert.equal(api.locationLabel({...record,location:{scope:'Unknown',label:'Do not infer this'}}),'Location unknown');
assert.deepEqual(api.sourceStates({...record,location:{scope:'Unknown',codes:['FL']}}),[]);
assert.equal(api.filterEvents([record],'weather','US:FL').length,1);
assert.equal(api.filterEvents([record],'weather','US:CA').length,0);
assert.equal(api.filterEvents([record],'all','Unknown').length,0);
assert.equal(api.externalUrl('javascript:alert(1)'),null);
assert.equal(api.externalUrl('https://user:password@example.com'),null);
assert.equal(api.guideUrl('//example.com/'),null);
assert.equal(api.guideUrl('/emergencies/power-outage/?place=home'),null);
assert.equal(api.exactGuides({...record,guides:[...record.guides,record.guides[0],{title:'bad',url:'https://example.com'}]}).length,2);
assert.throws(()=>api.normalizeSnapshot({events:[],sources:[]}));
assert.equal(api.normalizeSnapshot({...snapshot,events:[record,{...record,url:'javascript:alert(1)'}]}).events.length,1);
assert.equal(api.stamp(null),'Not provided');
assert.equal(api.normalizeSnapshot({...snapshot,events:[{...record,source:{...record.source,kind:'news'}}]}).events.length,0,'News without attribution and licensed source URLs must fail closed');
const selectionSources=[snapshot.sources[0],{...snapshot.sources[0],id:'test-second-source'},{...snapshot.sources[0],id:'test-news-source'}];
const selectionRecords=[record,{...record,id:'test-second',category:'recall',source:{...record.source,id:'test-second-source'},updatedAt:iso(-7200000)},{...record,id:'test-news',category:'news',source:{...record.source,id:'test-news-source',kind:'news'},updatedAt:iso(-10800000)},{...record,id:'test-duplicate-category',updatedAt:iso(-1000)},{...record,id:'test-expired',category:'earthquake',expiresAt:iso(-1000),updatedAt:iso(0)}];
const selected=api.selectHomeEvents({...snapshot,sources:selectionSources,events:selectionRecords},now);
assert.equal(selected.length,3);assert.equal(selected.filter(event=>event.source.kind==='news').length,1);
assert.equal(new Set(selected.map(event=>event.category)).size,3,'Homepage should diversify categories');
assert(!selected.some(event=>event.id==='test-expired'),'Expired records must not displace available current records');
assert.deepEqual(selected.map(event=>event.id),api.selectHomeEvents({...snapshot,sources:selectionSources,events:[...selectionRecords].reverse()},now).map(event=>event.id),'Homepage selection is deterministic independent of input order');
assert.equal(api.selectHomeEvents({...snapshot,sources:selectionSources,events:selectionRecords.map(event=>({...event,source:{...event.source,kind:'news'}}))},now).length,1,'Homepage uses at most one news record');
assert.equal(api.displaySummary({...record,displaySummary:null,summary:'HLSSGX * WHAT...THIS IS TECHNICAL'}),'Read the linked source for this report’s full details.');
assert.equal(api.displaySummary({...record,displaySummary:null,summary:'A complete source sentence is available. A second sentence is unfinished…'}),'Read the linked source for this report’s full details.');
assert.equal(api.displaySummary({...record,displaySummary:null,summary:'An unfinished source fragment without punctuation'}),'Read the linked source for this report’s full details.');
class Element {
 constructor(tag='div'){this.tagName=tag.toUpperCase();this.children=[];this.attrs={};this.events={};this.hidden=false;this.value='';this.textContent='';this.className='';this.selectors={};this.open=false;}
 append(...children){for(const child of children){child.parentElement=this;this.children.push(child);for(const node of flatten(child)){node.isConnected=true;node.ownerDocument=this.ownerDocument;}}}
 replaceChildren(...children){for(const child of this.children)for(const node of flatten(child))node.isConnected=false;this.children=[];this.append(...children);}
 setAttribute(key,value){this.attrs[key]=String(value);}
 getAttribute(key){return this.attrs[key]??this[key]??null;}
 addEventListener(key,fn){const old=this.events[key];this.events[key]=(...args)=>{old?.(...args);fn(...args);};}
 focus(options){this.focused=true;this.focusOptions=options;this.ownerDocument.activeElement=this;}
 closest(selector){let node=this;while(node){if(matches(node,selector))return node;node=node.parentElement;}return null;}
 querySelectorAll(selector){return flatten(this).slice(1).filter(node=>matches(node,selector));}
 querySelector(selector){return this.selectors[selector]||this.querySelectorAll(selector)[0]||null;}
}
function flatten(node){return [node,...node.children.flatMap(flatten)];}
function allText(node){return flatten(node).map(node=>node.textContent||'').join(' ');}
function matches(node,selector){
 const parts=selector.split(' ');if(parts.length>1)return matches(node,parts.at(-1))&&Boolean(node.parentElement?.closest(parts.slice(0,-1).join(' ')));
 const tag=selector.match(/^[a-z][a-z0-9]*/i)?.[0];if(tag&&node.tagName!==tag.toUpperCase())return false;
 for(const name of selector.matchAll(/\.([a-z-]+)/g))if(!node.className.split(' ').includes(name[1]))return false;
 for(const attr of selector.matchAll(/\[([^\]=]+)(?:="([^"]*)")?\]/g)){const value=node.getAttribute(attr[1]);if(attr[1]==='open'?!node.open:attr[2]!==undefined?value!==attr[2]:value==null)return false;}
 return true;
}
function fixture(modes=['index'],{stored=null,storedZip=null,storedArea=null,attempted=false,geo=false,geoThrows=false,areaLookup=null,blockedStorage=false,blockedHistory=false,blockedSession=false,savedState=null,session={},search='?id=test-only-record',referrer=''}={}){
 const document={title:'',hidden:false,referrer,events:{},activeElement:null,addEventListener:Element.prototype.addEventListener,createElement(tag){const node=new Element(tag);node.ownerDocument=this;return node;}};
 const keys=['status','status-detail','cards','fallback','filters','category','location','reset','count','empty','source-health','sources','detail','detail-fallback','more','zip-form','zip','zip-submit','zip-status','zip-clear','area-heading','area-note','group-nav','history','history-label','options','back','geolocate','area-choices'];
 const roots=modes.map(mode=>{const root=document.createElement('main');root.setAttribute('data-briefing',mode);for(const key of keys){const node=document.createElement();root.selectors['[data-briefing-'+key+']']=node;root.append(node);}const options=root.selectors['[data-briefing-options]'];options.setAttribute('data-briefing-options','');options.append(document.createElement('summary'));root.selectors['.briefing-fallback-intro']=document.createElement();return root;});document.querySelectorAll=()=>roots;
 const geoCalls=[],calls=[],writes=[],historyCalls=[],scrolls=[],frames=[],timers=new Map(),sessionMap=new Map(Object.entries(session));let nextTimer=0,clockNow=now;
 const localMap=new Map([[api.LOCATION_KEY,stored],[api.ZIP_KEY,storedZip],[api.AREA_KEY,storedArea?JSON.stringify(storedArea):null],[api.GEO_ATTEMPT_KEY,attempted?'1':null]]);
 class ClockDate extends Date{constructor(...args){super(...(args.length?args:[clockNow]));}static now(){return clockNow;}}
 let state=savedState?{unrelated:'preserve',ozBriefing:savedState}:{unrelated:'preserve'};
 const history={length:2,get state(){if(blockedHistory)throw Error('blocked');return state;},replaceState(...args){if(blockedHistory)throw Error('blocked');state=args[0];historyCalls.push(args);},back(){this.backCalled=true;}};
 const window={OspreyAreaLookup:areaLookup,location:{search,origin:'https://example.com'},history,events:{},scrollY:0,addEventListener:Element.prototype.addEventListener,requestAnimationFrame:fn=>frames.push(fn),scrollTo(options){this.scrollY=options.top;scrolls.push(options);}};
 vm.runInNewContext(code,{document,window,navigator:geo?{geolocation:{getCurrentPosition(success,error,options){if(geoThrows)throw Error('blocked');geoCalls.push({success,error,options});}}}:{},URL,URLSearchParams,Date:ClockDate,AbortController,
  localStorage:{getItem:key=>{if(blockedStorage)throw Error();return localMap.get(key)||null;},setItem:(k,v)=>{if(blockedStorage)throw Error();localMap.set(k,v);writes.push([k,v]);},removeItem:k=>{if(blockedStorage)throw Error();localMap.delete(k);writes.push([k,null]);}},
  sessionStorage:{getItem:key=>{if(blockedSession)throw Error();return sessionMap.get(key)||null;},setItem:(k,v)=>{if(blockedSession)throw Error();sessionMap.set(k,v);},removeItem:key=>{if(blockedSession)throw Error();sessionMap.delete(key);}},
  setTimeout:(fn,delay)=>{timers.set(++nextTimer,{fn,at:clockNow+delay,delay});return nextTimer;},clearTimeout:id=>timers.delete(id),
  fetch:(url,options)=>new Promise((resolve,reject)=>calls.push({url,options,resolve,reject}))});
 return {roots,calls,geoCalls,localMap,writes,document,window,timers,sessionMap,historyCalls,scrolls,flushFrames(){while(frames.length)frames.shift()();},advance(ms){clockNow+=ms;let n=0;while(true){const next=[...timers].filter(([,t])=>t.at<=clockNow).sort((a,b)=>a[1].at-b[1].at)[0];if(!next)break;if(++n>30)throw Error('Recurring timer');timers.delete(next[0]);next[1].fn();}},visible(value){document.hidden=!value;document.events.visibilitychange?.();}};
}
const tick=()=>new Promise(resolve=>setImmediate(resolve));
const get=(fx,key,index=0)=>fx.roots[index].querySelector('[data-briefing-'+key+']');
async function resolve(fx,data=snapshot,frames=true){fx.calls[0].resolve({ok:true,json:async()=>data});await tick();if(frames)fx.flushFrames();}
function change(fx,key,value){get(fx,key).value=value;get(fx,key).events.change();}
function historyOn(fx){get(fx,'history').checked=true;get(fx,'history').events.change();}
function submit(fx,zip){get(fx,'zip').value=zip;get(fx,'zip-form').events.submit({preventDefault(){}});}
function groupButton(fx,key){return get(fx,'group-nav').children.find(node=>node.getAttribute('data-group')===key);}
const zipData={schemaVersion:1,source:{vintage:'2020'},unsupportedStates:['CT'],states:{FL:{name:'Florida'},KY:{name:'Kentucky'},TN:{name:'Tennessee'},CT:{name:'Connecticut'},PR:{name:'Puerto Rico'}},counties:{'12001':{name:'Alachua County',state:'FL'},'21047':{name:'Christian County',state:'KY'},'47125':{name:'Montgomery County',state:'TN'},'09011':{name:'New London County',state:'CT'},'72127':{name:'San Juan',state:'PR'}},zipAreas:{'32601':['12001'],'42223':['21047','47125'],'06331':['09011'],'00901':['72127'],'00001':['09011','12001']}};
const news={...record,source:{...record.source,kind:'news',licenseUrl:'https://creativecommons.org/licenses/by/4.0/',rightsUrl:'https://example.com/rights'},attribution:'Test-only author and publisher attribution',instructions:'MUST NOT PRESENT AS OFFICIAL'};
const localRecord={...record,source:{...record.source,id:'nws'},geo:{countyFips:['12001'],zoneIds:[],sameCodes:[]}};
const zoneRecord={...localRecord,id:'test-zone-only',geo:{countyFips:[],zoneIds:['FLZ001'],sameCodes:[]}};
const recallRecord={...record,id:'test-recall',category:'recall',source:{...record.source,id:'fda'},location:{scope:'US',codes:[]}};
const cyberRecord={...record,id:'test-cyber',category:'cyber',source:{...record.source,id:'cisa-kev'},location:{scope:'Unknown',codes:[]}};
const unknownRecord={...record,id:'test-unknown',location:{scope:'Unknown',codes:[]}};
const zipSnapshot={...snapshot,events:[localRecord,zoneRecord,recallRecord,cyberRecord,unknownRecord]};
const manySnapshot={...snapshot,events:Array.from({length:23},(_,i)=>({...record,id:'test-only-'+i}))};
(async()=>{
 const index=fixture(['index'],{stored:'US:FL'});await resolve(index);
 assert.equal(index.calls.length,1);assert.equal(index.calls[0].url,'/api/briefing');assert.equal(index.calls[0].options.credentials,'omit');assert.equal(index.timers.size,1);
 assert.equal(get(index,'location').value,'US:FL');assert.equal(get(index,'cards').children.length,1);assert(get(index,'fallback').hidden);assert(!get(index,'filters').hidden);
 assert(!flatten(get(index,'cards')).some(node=>node.tagName==='SCRIPT'));assert.match(allText(get(index,'cards')),/Literal <script> text/);
 change(index,'location','International');assert(get(index,'cards').hidden);assert.match(allText(get(index,'empty')),/Not an all-clear/);assert.equal(index.calls.length,1);
 get(index,'reset').events.click();assert.equal(get(index,'cards').children.length,1);assert.equal(get(index,'location').value,'all');
 const options=get(index,'options');options.open=true;let escaped=false;options.events.keydown({key:'Escape',preventDefault(){escaped=true;}});assert(escaped);assert(!options.open);assert(index.document.activeElement===options.querySelector('summary'));
 options.open=true;index.document.events.click({target:options.querySelector('summary')});assert(options.open,'Clicks inside filters keep them open');index.document.events.click({target:get(index,'category')});assert(!options.open,'An outside click dismisses filters');options.open=true;index.document.events.focusin({target:get(index,'category')});assert(!options.open,'Tabbing out dismisses the overlay');
 options.open=true;change(index,'location','International');assert(options.open,'Location changes keep keyboard select navigation available');assert.match(index.roots[0].querySelector('.briefing-fallback-intro').textContent,/No reports match/);assert(!index.roots[0].querySelector('.briefing-fallback-intro').textContent.includes('load'));get(index,'reset').events.click();
 const shared=fixture(['home','index','event']);await resolve(shared,{...snapshot,storageNote:'Preview schedule is inactive.'});assert.equal(shared.calls.length,1);
 for(const root of shared.roots)assert.match(root.querySelector('[data-briefing-status-detail]').textContent,/Preview schedule is inactive/);
 const detail=get(shared,'detail',2);assert.equal(flatten(detail).filter(node=>node.tagName==='SECTION').length,6);assert.match(allText(detail),/Test-only source instructions/);
 assert(detail.children[0].querySelector('.briefing-card-source a'),'Detail header exposes the original source before guides');assert.match(allText(detail.children[0].querySelector('.briefing-card-source')),/checked/);
 const detailNodes=flatten(detail);assert(detailNodes.findIndex(n=>n.id==='related-guides')<detailNodes.findIndex(n=>n.id==='official-instructions'));assert(detailNodes.findIndex(n=>n.id==='related-guides')<detailNodes.findIndex(n=>n.className==='briefing-facts'));
 const reported=fixture(['home','event']);await resolve(reported,{...snapshot,events:[news]});
 for(const node of [get(reported,'cards'),get(reported,'detail',1)]){assert.match(allText(node),/Test-only author and publisher/);assert(flatten(node).some(n=>n.href===news.source.licenseUrl));assert(flatten(node).some(n=>n.href===news.url));assert(!allText(node).includes('MUST NOT PRESENT AS OFFICIAL'));}
 const newsNodes=flatten(get(reported,'cards'));assert(newsNodes.findIndex(n=>n.className==='briefing-attribution')<newsNodes.findIndex(n=>n.className==='briefing-card-summary'));
 const shown=fixture(['home','event']);await resolve(shown,{...snapshot,events:[{...record,displayTitle:'Readable source headline',displaySummary:'A complete source-supported sentence.',sourceUrl:'https://example.com/current',sourceUrlKind:'current-alerts-map',sourceLinkLabel:'Check current area alerts',geo:{incomplete:true}}]});
 const card=get(shown,'cards').children[0];assert.equal(card.querySelector('h3 a').textContent,'Readable source headline');assert.match(allText(card),/complete source-supported sentence/);assert.match(allText(card.querySelector('.briefing-card-source')),/checked/);assert.match(allText(card.querySelector('.briefing-card-metadata')),/Original source data record/);assert.match(allText(card.querySelector('.briefing-card-metadata')),/geographic list is incomplete/);assert.equal(card.querySelectorAll('.briefing-card-guides a').length,2);assert.match(allText(get(shown,'detail',1)),/Original source headline/);
 const recallDetail=fixture(['event'],{search:'?id='+recallRecord.id});await resolve(recallDetail,{...snapshot,events:[recallRecord]});const recallArticle=get(recallDetail,'detail');assert(recallArticle.children[0].querySelector('.briefing-source-action'),'Recall detail puts its product-specific source action before secondary preparedness guides');
 const catalog=fixture(['home','event'],{search:'?id='+cyberRecord.id});await resolve(catalog,{...snapshot,events:[{...cyberRecord,sourceUrlKind:'source-catalog',sourceLinkLabel:'Open the CISA catalog; search CVE-2026-12345'}]});for(const node of [get(catalog,'cards'),get(catalog,'detail',1)]){assert.match(allText(node),/CISA catalog \(search by CVE\)/);assert(!allText(node).includes('original data record'));assert(!allText(node).includes('Original source data record'));assert.match(allText(node),/CVE-2026-12345/);}
 const counts=fixture();await resolve(counts,{...snapshot,sources:[{...snapshot.sources[0],coverage:{status:'partial',storedCount:150,receivedCount:125,publicCount:120,limit:150,sourceDroppedCount:4,publicDroppedCount:30}}]});const sourceCounts=allText(get(counts,'sources'));for(const text of ['120 records included','150 records stored','125 source records received','4 records omitted','30 stored records omitted'])assert(sourceCounts.includes(text));assert(!sourceCounts.includes('stored from'));
 const separateNotices=[{...localRecord,id:'notice-a',sourceEventId:'explicit-a',title:'Same source headline',instructions:'Area A instructions.',geo:{countyFips:['12001'],zoneIds:['FLZ001']},relatedIds:[]},{...localRecord,id:'notice-b',sourceEventId:'explicit-b',title:'Same source headline',instructions:'Area B instructions.',geo:{countyFips:['12001'],zoneIds:['FLZ002']},relatedIds:['explicit-a']},{...localRecord,id:'notice-c',sourceEventId:'explicit-c',title:'Same source headline',instructions:'Separate unreferenced instructions.',geo:{countyFips:['12001'],zoneIds:['FLZ001']},relatedIds:[]}];
 const separate=fixture();await resolve(separate,{...snapshot,events:separateNotices});assert.equal(get(separate,'cards').children.length,3,'Duplicate titles/county alone are never grouped; explicit references with different zone scopes also stay distinct');for(const notice of separateNotices)assert(get(separate,'cards').querySelectorAll('a[href]').some(link=>link.getAttribute('href')===api.eventUrl(notice)),'Every original record remains reachable');
 const many=fixture();await resolve(many,manySnapshot);assert.equal(get(many,'cards').children.length,6);get(many,'more').events.click();assert.equal(get(many,'cards').children.length,12);assert(many.document.activeElement===get(many,'cards').children[6].querySelector('h3 a'),'Pagination focuses first new headline');assert.equal(many.calls.length,1);
 const history=fixture();await resolve(history,{...snapshot,events:[record,{...record,id:'expired',expiresAt:iso(-1)},{...news,id:'background',relevance:'background'}]});assert.equal(get(history,'cards').children.length,1);assert.match(get(history,'history-label').textContent,/\(2\)/);historyOn(history);assert.equal(get(history,'cards').children.length,3);assert.match(allText(get(history,'cards')),/validity time has passed/);assert.equal(api.selectHomeEvents({...snapshot,events:[{...news,relevance:'background'},{...record,expiresAt:iso(-1)}]}).length,0);
 const diversity=api.prioritizeEvents([...Array.from({length:30},(_,i)=>({...record,id:'weather-'+i})),recallRecord,cyberRecord,{...record,id:'earthquake',category:'earthquake'},news],[...snapshot.sources,...['fda','cisa-kev'].map(id=>({...snapshot.sources[0],id}))]).slice(0,6);assert(new Set(diversity.map(e=>e.category)).size>=4,'First six should not all be weather');
 const missing=fixture(['event'],{search:'?id=missing'});await resolve(missing);assert.match(get(missing,'detail-fallback').textContent,/absence is not an all-clear/);
 const seed=fixture();await resolve(seed,{...snapshot,storageStatus:'initial-snapshot',storageNote:'Production schedule has not written its first snapshot.'});assert.match(get(seed,'status').textContent,/Initial snapshot/);assert(!get(seed,'status').textContent.includes('Preview'),'Initial storage alone never claims schedules are inactive');
 const failed=fixture();failed.calls[0].reject(Error('offline'));await tick();assert.match(get(failed,'status').textContent,/Current conditions are unknown/);assert(!get(failed,'fallback').hidden);
 const blocked=fixture(['index'],{blockedStorage:true,blockedHistory:true,blockedSession:true});await resolve(blocked);change(blocked,'location','US:FL');assert.equal(get(blocked,'cards').children.length,1);
 assert.equal(api.resolveZipArea(zipData,'00901').zip,'00901');assert.deepEqual(api.resolveZipArea(zipData,'42223').counties.map(c=>c.code),['21047','47125']);for(const zip of ['06331','00001'])assert.equal(api.resolveZipArea(zipData,zip).status,'unsupported');assert.equal(api.resolveZipArea(zipData,'00501').status,'unmapped');assert.equal(api.resolveZipArea(zipData,'12abc').status,'invalid');assert.throws(()=>api.resolveZipArea({},'32601'));
 const partition=api.partitionAreaEvents(zipSnapshot.events,api.resolveZipArea(zipData,'32601'),'all');assert.equal(partition.local.length,1);assert.equal(partition.products.length,2);assert.equal(partition.other.length,2);
 const large=api.normalizeSnapshot({...snapshot,events:[...Array.from({length:600},(_,i)=>({...unknownRecord,id:'large-'+i})),localRecord,recallRecord,{...news,id:'late-news'}]});assert.equal(large.events.length,603);assert.equal(api.partitionAreaEvents(large.events,api.resolveZipArea(zipData,'32601'),'all').local.length,1);assert(large.events.some(e=>e.id==='late-news'));
 const zip=fixture();await resolve(zip,zipSnapshot);submit(zip,'12abc');assert.equal(zip.calls.length,1);assert.match(get(zip,'zip-status').textContent,/five-digit/);assert.equal(get(zip,'zip').getAttribute('aria-invalid'),'true');assert(zip.document.activeElement===get(zip,'zip'));
 submit(zip,'32601');assert(get(zip,'zip-submit').disabled);assert.equal(get(zip,'zip').getAttribute('aria-busy'),'true');assert.equal(get(zip,'zip').getAttribute('aria-invalid'),'false');submit(zip,'32601');assert.equal(zip.calls.length,2);assert.equal(zip.calls[1].url,'/briefing/zip-areas.json');assert.equal(zip.calls[1].options.credentials,'omit');get(zip,'zip-clear').events.click();zip.calls[1].resolve({ok:true,json:async()=>zipData});await tick();assert.equal(get(zip,'cards').children.length,5);assert(get(zip,'group-nav').hidden);assert(!get(zip,'zip-submit').disabled);assert.equal(get(zip,'zip').getAttribute('aria-busy'),'false');
 submit(zip,'32601');await tick();assert.equal(get(zip,'cards').children.length,1);assert.match(get(zip,'area-note').textContent,/Alachua/);assert.match(groupButton(zip,'products').textContent,/2/);assert.match(groupButton(zip,'other').textContent,/2/);
 change(zip,'category','recall');assert.equal(get(zip,'cards').children.length,1);assert.equal(groupButton(zip,'products').getAttribute('aria-pressed'),'true');assert.match(get(zip,'count').textContent,/1 of 1 product/);assert(get(zip,'empty').hidden,'ZIP+recalls must not show a misleading empty-local message');assert(get(zip,'cards').querySelector('.briefing-source-action'));
 change(zip,'category','all');change(zip,'location','US:FL');assert.equal(get(zip,'zip').value,'');assert.equal(get(zip,'cards').children.length,2);assert.match(groupButton(zip,'products').textContent,/2/);
 assert(get(zip,'location').children.some(n=>n.value==='US:CT'));assert(get(zip,'location').children.some(n=>n.value==='US:PR'));change(zip,'location','US:CT');assert.match(groupButton(zip,'local').textContent,/0/);assert.equal(get(zip,'cards').children.length,2);groupButton(zip,'local').focus();groupButton(zip,'local').events.click();assert(zip.document.activeElement===groupButton(zip,'local'),'Keyboard group switching focuses the replacement control');assert.match(allText(get(zip,'empty')),/Not an all-clear/);
 submit(zip,'00501');await tick();assert.match(get(zip,'zip-status').textContent,/not in this geographic/);submit(zip,'06331');await tick();assert.match(get(zip,'zip-status').textContent,/Connecticut county matching/);get(zip,'reset').events.click();assert.equal(get(zip,'location').value,'all');assert.equal(get(zip,'category').value,'all');assert.equal(get(zip,'zip').value,'');assert.equal(zip.calls.length,2);
 const restoredZip=fixture(['index'],{storedZip:'00901'});await resolve(restoredZip,zipSnapshot);restoredZip.calls[1].resolve({ok:true,json:async()=>zipData});await tick();assert.match(get(restoredZip,'zip-status').textContent,/00901/);
 for(const bad of ['offline','corrupt']){const fx=fixture(['index'],{blockedStorage:true});await resolve(fx);submit(fx,'32601');if(bad==='offline')fx.calls[1].reject(Error('offline'));else fx.calls[1].resolve({ok:true,json:async()=>({bad:true})});await tick();assert.match(get(fx,'zip-status').textContent,/lookup unavailable/);assert.equal(get(fx,'cards').children.length,1);assert(!get(fx,'zip-submit').disabled);assert.equal(get(fx,'zip').getAttribute('aria-busy'),'false');}
 const interrupted=fixture();await resolve(interrupted,zipSnapshot);submit(interrupted,'32601');get(interrupted,'zip').value='00901';get(interrupted,'zip').events.input();interrupted.calls[1].resolve({ok:true,json:async()=>zipData});await tick();assert(get(interrupted,'group-nav').hidden);submit(interrupted,'00901');await tick();assert.match(get(interrupted,'zip-status').textContent,/00901/);assert.equal(interrupted.calls.length,2);
 const timed=fixture(['home','index','event'],{stored:'US:FL'});const timedSnapshot={...snapshot,lastSuccessfulAt:iso(0),sources:snapshot.sources.map(source=>({...source,lastSuccessAt:iso(0)})),events:Array.from({length:23},(_,i)=>({...record,id:i===0?record.id:'time-'+i,expiresAt:i===0?iso(10):iso(60000),endsAt:null,lastCheckedAt:iso(0)}))};await resolve(timed,timedSnapshot);
 const tr=timed.roots[1],tg=key=>tr.querySelector('[data-briefing-'+key+']');tg('more').events.click();assert.equal(tg('cards').children.length,12);const focused=tg('cards').children.find(c=>c.getAttribute('data-record-id')===record.id)?.querySelector('h3 a');assert(focused);focused.focus();timed.window.scrollY=900;const detailHeader=get(timed,'detail',2).children[0];timed.advance(11);assert.equal(tg('cards').children.length,12);assert(!tg('cards').children.some(c=>c.getAttribute('data-record-id')===record.id));assert(timed.document.activeElement===tg('count'),'Expired focused record moves focus to visible status');assert.equal(tg('location').value,'US:FL');assert.match(tg('history-label').textContent,/\(1\)/);assert.equal(timed.window.history.state.ozBriefing.limits.local,12);assert(get(timed,'detail',2).children[0]===detailHeader,'Detail nodes stable');assert.match(allText(detailHeader),/does not mean the threat has ended/);assert.equal(timed.calls.length,1);
 timed.advance(60000);assert.equal(tg('cards').children.length,0);tg('history').checked=true;tg('history').events.change();const retained=tg('cards').children[0];timed.advance(api.STALE_AFTER_MS);assert(tg('cards').children[0]===retained,'Staleness only updates labels');assert.match(allText(tg('cards')),/Source refresh overdue/);assert.match(allText(tg('sources')),/Source is stale/);assert.equal(timed.timers.size,0);assert.equal(timed.calls.length,1);
 const hidden=fixture();await resolve(hidden);hidden.visible(false);hidden.advance(15*3600000);hidden.visible(true);assert.equal(get(hidden,'cards').children.length,0);assert.equal(get(hidden,'status').getAttribute('data-state'),'stale');assert.equal(hidden.calls.length,1);
 // Return state contains UI only. ZIP/category/pagination and scroll never enter a URL.
 const returning=fixture();await resolve(returning,manySnapshot);change(returning,'category','weather');get(returning,'more').events.click();returning.window.scrollY=1475;const focusLink=get(returning,'cards').children[8].querySelector('h3 a');returning.roots[0].events.click({target:focusLink});returning.window.events.pagehide();const saved=returning.window.history.state.ozBriefing;assert.equal(saved.limits.all,12);assert.equal(saved.scrollY,1475);assert.equal(saved.category,'weather');assert(returning.historyCalls.every(args=>args.length===2));assert.equal(returning.window.history.state.unrelated,'preserve');assert(!JSON.stringify(saved).includes(record.summary));
 const back=fixture(['index'],{savedState:saved});await resolve(back,manySnapshot);assert.equal(get(back,'category').value,'weather');assert.equal(get(back,'cards').children.length,12);assert.equal(back.window.scrollY,1475);assert.equal(back.document.activeElement.getAttribute('href'),focusLink.href);
 const detailReturn=fixture(['event'],{session:{[api.RETURN_KEY]:JSON.stringify(saved)},referrer:'https://example.com/briefing/'});await resolve(detailReturn);assert.match(get(detailReturn,'back').textContent,/Back to your results/);get(detailReturn,'back').events.click({preventDefault(){}});assert(detailReturn.window.history.backCalled);
 const direct=fixture(['event']);await resolve(direct);assert(!get(direct,'back').events.click,'Direct visits keep a safe plain briefing link');
 const sessionBack=fixture(['index'],{blockedHistory:true,session:{[api.RETURN_KEY]:JSON.stringify(saved)}});await resolve(sessionBack,manySnapshot);assert.equal(get(sessionBack,'cards').children.length,12);assert.equal(sessionBack.window.scrollY,1475);
 const cancelledReturn=fixture(['index'],{savedState:saved});await resolve(cancelledReturn,manySnapshot,false);change(cancelledReturn,'category','all');cancelledReturn.flushFrames();assert.equal(cancelledReturn.scrolls.length,0,'User interaction cancels delayed scroll restoration');
 const zipState={...saved,zip:'32601',category:'recall',group:'products',limits:{...saved.limits,products:12},scrollY:450};const zipBack=fixture(['index'],{savedState:zipState});await resolve(zipBack,zipSnapshot);assert.equal(zipBack.scrolls.length,0);zipBack.calls[1].resolve({ok:true,json:async()=>zipData});await tick();zipBack.flushFrames();assert.equal(get(zipBack,'zip').value,'32601');assert.equal(get(zipBack,'category').value,'recall');assert.equal(groupButton(zipBack,'products').getAttribute('aria-pressed'),'true');assert.equal(zipBack.window.scrollY,450);assert.equal(zipBack.calls.length,2);
 assert.equal(api.validViewState({...saved,path:'/other/'}),null);assert.equal(api.validViewState({...saved,at:now-90000000}),null);
 // Unified city/state input. Ambiguous cities stay unselected until a keyboard choice.
 const cityArea={kind:'city',label:'Gainesville, FL',state:'FL',counties:[{code:'12001',name:'Alachua County',state:'FL'}]};
 const secondCity={...cityArea,label:'Gainesville, TX',state:'TX',counties:[{code:'48097',name:'Cooke County',state:'TX'}]};
 const lookup={searchAreas(data,query){if(data.bad)throw Error('bad mapping');return query.toLowerCase().startsWith('gainesville')?{status:'found',matches:query.includes(',')?[cityArea]:[cityArea,secondCity]}:{status:'unmapped',matches:[]};},resolveCoordinates(data,lat,lon,accuracy){if(data.bad)throw Error('bad geometry');if(lat===51)return {status:'unmapped',matches:[]};if(accuracy>50000)return {status:'imprecise',matches:[]};return {status:accuracy>1000?'ambiguous':'found',matches:[{...cityArea,kind:'geolocation',label:'Alachua County, FL'}]};}};
 const city=fixture(['index'],{areaLookup:lookup,attempted:true});await resolve(city,zipSnapshot);submit(city,'fl');assert.equal(get(city,'location').value,'US:FL');assert.equal(city.calls.length,1);assert.match(get(city,'zip-status').textContent,/Florida/);submit(city,'Connecticut');assert.equal(get(city,'location').value,'US:CT');groupButton(city,'local').events.click();assert.match(get(city,'area-note').textContent,/broad state/);
 submit(city,'Gainesville');assert(get(city,'zip-submit').disabled);assert.equal(city.calls[1].url,api.PLACE_DATA_URL);city.calls[1].resolve({ok:true,json:async()=>({})});await tick();assert(!get(city,'area-choices').hidden);assert.equal(get(city,'location').value,'US:CT','Ambiguous city does not silently choose a state');assert.equal(get(city,'zip').getAttribute('aria-expanded'),'true');
 const key=(node,value)=>node.events.keydown({key:value,preventDefault(){}});key(get(city,'zip'),'ArrowDown');const choiceButtons=get(city,'area-choices').querySelectorAll('button');assert(city.document.activeElement===choiceButtons[0]);key(get(city,'area-choices'),'ArrowDown');assert(city.document.activeElement===choiceButtons[1]);key(get(city,'area-choices'),'Home');assert(city.document.activeElement===choiceButtons[0]);key(get(city,'area-choices'),'End');assert(city.document.activeElement===choiceButtons[1]);key(get(city,'area-choices'),'Escape');assert(get(city,'area-choices').hidden);assert(city.document.activeElement===get(city,'zip'));
 submit(city,'Gainesville');await tick();get(city,'area-choices').querySelector('button').events.click();assert.equal(get(city,'cards').children.length,1);assert.match(get(city,'area-note').textContent,/Alachua|Gainesville/);assert(get(city,'area-choices').hidden);assert.equal(get(city,'zip').value,'Gainesville, FL');assert.equal(city.calls.length,2);assert.equal(JSON.parse(city.localMap.get(api.AREA_KEY)).kind,'city');assert.match(get(city,'area-note').textContent,/NWS county-coded/);assert.equal(groupButton(city,'other').textContent,'Other · 2');
 const mixedLookup={...lookup,searchAreas(){return {status:'found',matches:[{...cityArea,label:'New London city, CT',unsupported:true,counties:[{code:'09011',name:'Old New London County',state:'CT'}]},cityArea,secondCity]};}};const mixedCity=fixture(['index'],{attempted:true,areaLookup:mixedLookup});await resolve(mixedCity,zipSnapshot);submit(mixedCity,'New London');mixedCity.calls[1].resolve({ok:true,json:async()=>({})});await tick();const mixedButtons=get(mixedCity,'area-choices').querySelectorAll('button');assert(mixedButtons[0].disabled);key(get(mixedCity,'zip'),'ArrowDown');assert(mixedCity.document.activeElement===mixedButtons[1]);key(get(mixedCity,'area-choices'),'ArrowDown');assert(mixedCity.document.activeElement===mixedButtons[2]);key(get(mixedCity,'area-choices'),'ArrowDown');assert(mixedCity.document.activeElement===mixedButtons[1]);mixedButtons[0].events.click();assert(get(mixedCity,'group-nav').hidden);
 const citySaved=city.window.history.state.ozBriefing;const cityBack=fixture(['index'],{savedState:citySaved,geo:true,areaLookup:lookup});await resolve(cityBack,zipSnapshot);assert.equal(cityBack.geoCalls.length,0);assert.equal(cityBack.calls.length,1);assert.equal(get(cityBack,'zip').value,'Gainesville, FL');
 const sanitized=api.validArea({...cityArea,latitude:29.651634,longitude:-82.324826,accuracy:40,coords:{latitude:29.651634},arbitrary:'discard'});assert(!JSON.stringify(sanitized).includes('latitude'));assert(!JSON.stringify(sanitized).includes('29.651634'));assert.equal(api.validArea({...cityArea,counties:[{code:'09001',name:'Historical county',state:'CT'}]}),null);
 // Automatic location starts after the visible controls' next frame, once only.
 const auto=fixture(['index'],{geo:true,areaLookup:lookup});await resolve(auto,zipSnapshot,false);assert.equal(auto.geoCalls.length,0);assert(!get(auto,'zip-form').hidden);auto.flushFrames();assert.equal(auto.geoCalls.length,1);assert(get(auto,'geolocate').disabled);get(auto,'geolocate').events.click();assert.equal(auto.geoCalls.length,1,'Repeated location clicks do not start duplicate requests');assert(!get(auto,'zip-submit').disabled);assert.equal(auto.localMap.get(api.GEO_ATTEMPT_KEY),'1');assert.deepEqual(JSON.parse(JSON.stringify(auto.geoCalls[0].options)),{enableHighAccuracy:false,maximumAge:0,timeout:10000});
 auto.geoCalls[0].success({coords:{latitude:29.651634,longitude:-82.324826,accuracy:80}});assert.equal(auto.calls[1].url,api.COUNTY_DATA_URL);assert.equal(auto.calls[1].options.credentials,'omit');auto.calls[1].resolve({ok:true,json:async()=>({})});await tick();assert.match(get(auto,'zip-status').textContent,/device-location county estimate/);assert.equal(get(auto,'cards').children.length,1);assert(!get(auto,'geolocate').disabled);assert.equal(JSON.parse(auto.localMap.get(api.AREA_KEY)).kind,'geolocation');
 const privacy=JSON.stringify({writes:auto.writes,session:[...auto.sessionMap],history:auto.historyCalls,requests:auto.calls.map(call=>[call.url,call.options])});for(const secret of ['29.651634','82.324826','latitude','longitude','coords'])assert(!privacy.includes(secret),'Coordinates must never be persisted or transmitted: '+secret);assert(auto.historyCalls.every(args=>args.length===2));
 const again=fixture(['index'],{geo:true,attempted:true});await resolve(again);assert.equal(again.geoCalls.length,0);
 for(const savedPreference of [{storedZip:'32601'},{stored:'US:FL'},{stored:'all'},{storedArea:cityArea}]){const fx=fixture(['index'],{...savedPreference,geo:true,areaLookup:lookup});await resolve(fx);assert.equal(fx.geoCalls.length,0,'Existing manual preference suppresses automatic location');}
 const corruptPreference=fixture(['index'],{geo:true,stored:'US:FL'});corruptPreference.localMap.set(api.AREA_KEY,'{bad json');await resolve(corruptPreference);assert.equal(corruptPreference.geoCalls.length,0);assert.equal(get(corruptPreference,'location').value,'US:FL');
 const noPromptStorage=fixture(['index'],{geo:true,blockedStorage:true,blockedSession:true});await resolve(noPromptStorage);assert.equal(noPromptStorage.geoCalls.length,0);get(noPromptStorage,'geolocate').events.click();assert.equal(noPromptStorage.geoCalls.length,1,'Explicit request still works without storage');noPromptStorage.geoCalls[0].error({code:1});assert.match(get(noPromptStorage,'zip-status').textContent,/not granted/);
 const sessionAttempt=fixture(['index'],{geo:true,blockedStorage:true});await resolve(sessionAttempt);assert.equal(sessionAttempt.geoCalls.length,1);assert.equal(sessionAttempt.sessionMap.get(api.GEO_ATTEMPT_KEY),'1');const sessionRepeat=fixture(['index'],{geo:true,blockedStorage:true,session:{[api.GEO_ATTEMPT_KEY]:'1'}});await resolve(sessionRepeat);assert.equal(sessionRepeat.geoCalls.length,0);
 for(const errorCode of [1,2,3]){const fx=fixture(['index'],{geo:true});await resolve(fx);fx.geoCalls[0].error({code:errorCode});assert(!get(fx,'geolocate').disabled);assert.match(get(fx,'zip-status').textContent,errorCode===1?/not granted/:errorCode===3?/timed out/:/could not be determined/);fx.advance(30000);assert.equal(fx.geoCalls.length,1,'No automatic retry after failure');get(fx,'geolocate').events.click();assert.equal(fx.geoCalls.length,2);}
 const permissionWait=fixture(['index'],{geo:true,areaLookup:lookup});await resolve(permissionWait);permissionWait.advance(api.GEO_DEADLINE_MS);assert.match(get(permissionWait,'zip-status').textContent,/timed out/);assert(!get(permissionWait,'geolocate').disabled);permissionWait.geoCalls[0].success({coords:{latitude:29,longitude:-82,accuracy:80}});assert.equal(permissionWait.calls.length,1,'Permission callback after independent deadline is ignored');
 const manualWins=fixture(['index'],{geo:true,areaLookup:lookup});await resolve(manualWins);submit(manualWins,'Florida');manualWins.geoCalls[0].success({coords:{latitude:29,longitude:-82,accuracy:80}});assert.equal(manualWins.calls.length,1);assert.equal(get(manualWins,'location').value,'US:FL');assert(!get(manualWins,'geolocate').disabled);
 const typingWins=fixture(['index'],{geo:true,areaLookup:lookup});await resolve(typingWins);get(typingWins,'zip').value='California';get(typingWins,'zip').events.input();typingWins.geoCalls[0].success({coords:{latitude:29,longitude:-82,accuracy:80}});assert.equal(typingWins.calls.length,1);assert.equal(get(typingWins,'zip').value,'California');
 const clearWins=fixture(['index'],{geo:true,areaLookup:lookup});await resolve(clearWins);clearWins.geoCalls[0].success({coords:{latitude:29,longitude:-82,accuracy:80}});get(clearWins,'zip-clear').events.click();clearWins.calls[1].resolve({ok:true,json:async()=>({})});await tick();assert(get(clearWins,'group-nav').hidden);assert.equal(get(clearWins,'zip').value,'');assert(!get(clearWins,'geolocate').disabled);
 const stalledGeometry=fixture(['index'],{geo:true,areaLookup:lookup});await resolve(stalledGeometry);stalledGeometry.geoCalls[0].success({coords:{latitude:29,longitude:-82,accuracy:80}});stalledGeometry.advance(12000);await tick();assert(!get(stalledGeometry,'geolocate').disabled);assert.match(get(stalledGeometry,'zip-status').textContent,/lookup unavailable/);stalledGeometry.calls[1].resolve({ok:true,json:async()=>({})});await tick();assert(get(stalledGeometry,'group-nav').hidden);
 const noLocation=fixture(['index'],{geo:false});await resolve(noLocation);assert.match(get(noLocation,'zip-status').textContent,/unavailable in this browser/);submit(noLocation,'CA');assert.equal(get(noLocation,'location').value,'US:CA');
 const throwsLocation=fixture(['index'],{geo:true,geoThrows:true});await resolve(throwsLocation);assert.match(get(throwsLocation,'zip-status').textContent,/could not be determined/);assert(!get(throwsLocation,'geolocate').disabled);
 for(const [lat,accuracy,expected] of [[51,80,/No supported U.S./],[29,90000,/too imprecise/],[29,2000,/area choice/]]){const fx=fixture(['index'],{geo:true,areaLookup:lookup});await resolve(fx);fx.geoCalls[0].success({coords:{latitude:lat,longitude:-82,accuracy}});fx.calls[1].resolve({ok:true,json:async()=>({})});await tick();assert.match(get(fx,'zip-status').textContent,expected);assert(get(fx,'group-nav').hidden);if(accuracy===2000){assert(!get(fx,'area-choices').hidden);get(fx,'area-choices').querySelector('button').events.click();assert(!get(fx,'group-nav').hidden);}}
 for(const failure of ['network','geometry']){const fx=fixture(['index'],{geo:true,areaLookup:lookup});await resolve(fx);fx.geoCalls[0].success({coords:{latitude:29,longitude:-82,accuracy:80}});if(failure==='network')fx.calls[1].reject(Error('offline'));else fx.calls[1].resolve({ok:true,json:async()=>({bad:true})});await tick();assert.match(get(fx,'zip-status').textContent,/County lookup unavailable/);assert(!get(fx,'geolocate').disabled);submit(fx,'Texas');assert.equal(get(fx,'location').value,'US:TX');}
 const noHomePrompt=fixture(['home','event'],{geo:true,areaLookup:lookup});await resolve(noHomePrompt);assert.equal(noHomePrompt.geoCalls.length,0);assert.equal(noHomePrompt.calls.length,1);
 const cancelInitial=fixture(['index'],{geo:true});await resolve(cancelInitial,snapshot,false);submit(cancelInitial,'FL');cancelInitial.flushFrames();assert.equal(cancelInitial.geoCalls.length,0,'Manual selection before first paint cancels scheduled automatic request');
 const failedSnapshot=fixture(['index'],{geo:true});failedSnapshot.calls[0].reject(Error('offline'));await tick();failedSnapshot.flushFrames();assert(!get(failedSnapshot,'zip-form').hidden);assert.equal(failedSnapshot.geoCalls.length,1);submit(failedSnapshot,'California');assert.equal(get(failedSnapshot,'location').value,'US:CA');assert.match(get(failedSnapshot,'status').textContent,/Current conditions are unknown/);
 // Integration uses the exact shipped Census data and pure lookup module, not only stubs.
 const realLookup=require('../briefing/local-area-lookup.js'),realPlaces=JSON.parse(fs.readFileSync('briefing/place-areas.json','utf8')),realCounties=JSON.parse(fs.readFileSync('briefing/county-geometry.json','utf8'));
 const realCity=fixture(['index'],{attempted:true,areaLookup:realLookup});await resolve(realCity,zipSnapshot);submit(realCity,'Gainesville, FL');realCity.calls[1].resolve({ok:true,json:async()=>realPlaces});await tick();assert.equal(get(realCity,'cards').children.length,1);assert.match(get(realCity,'zip-status').textContent,/Gainesville city, FL/);submit(realCity,'New York, NY');await tick();assert.equal(JSON.parse(realCity.localMap.get(api.AREA_KEY)).counties.length,5,'Multicounty cities retain all five borough counties');submit(realCity,'New London');await tick();assert.equal(get(realCity,'area-choices').querySelectorAll('button').length,9);assert.equal(get(realCity,'area-choices').querySelectorAll('button').filter(button=>button.disabled).length,1,'Real ambiguous CT entry is visibly unavailable');
 submit(realCity,'Springfield');await tick();assert.equal(get(realCity,'area-choices').querySelectorAll('button').length,20);assert.match(get(realCity,'zip-status').textContent,/Showing 20 of [2-9][0-9]+ matches/);assert.equal(JSON.parse(realCity.localMap.get(api.AREA_KEY)).counties.length,5,'Truncated candidate lists never auto-select');
 const realGeo=fixture(['index'],{geo:true,areaLookup:realLookup});await resolve(realGeo,zipSnapshot);realGeo.geoCalls[0].success({coords:{latitude:29.651634,longitude:-82.324826,accuracy:80}});realGeo.calls[1].resolve({ok:true,json:async()=>realCounties});await tick();assert.match(get(realGeo,'zip-status').textContent,/Alachua County, FL/);assert.match(get(realGeo,'zip-status').textContent,/accuracy about 80 m/);assert.equal(get(realGeo,'cards').children.length,1);
 assert.match(allText(card.querySelector('.briefing-card-guides')),/Prepare for this/);assert.equal(card.querySelectorAll('.briefing-reading-icon').length,2);assert.match(allText(get(shown,'detail',1)),/Prepare for this/);
 const template=fs.readFileSync('scripts/build_briefing.py','utf8'),inputMarkup=template.match(/<input id="briefing-zip"[^>]*>/)[0];assert(!/\bname=/.test(inputMarkup));assert(template.includes('data-briefing-history'));assert(template.includes('census.gov/programs-surveys/geography/guidance/geo-areas/zctas.html'));assert(!code.includes('innerHTML'));assert(!code.includes('setInterval'));assert(code.includes('getCurrentPosition'));assert(!code.includes('watchPosition'));assert(!/fetch\([^)]*(?:latitude|longitude)/.test(code));assert(zip.calls.every(call=>!call.url.includes('32601')));
 console.log('PASS: Daily Brief unified locations, first-launch location privacy, compact current-first briefing, six-card diversity, honest group counts/history, visible sources, safe attribution, ZIP privacy/failures, local expiry regrouping/focus and private return restoration.');
})().catch(error=>{console.error(error);process.exitCode=1;});
